### ISSUE TITLE
Add Liberapay as donate / sponsor option

### ISSUE THREAD

**Issue by MagicLike** [openandroidinstaller-dev/openandroidinstaller#107]
[Liberapay](https://liberapay.com) is a FOSS platform for recurring donations. It does not have any fees from the platform itself, the only costs come from the payment providers. If you need any help setting up - I am always glad to do so!

**Comment by MagicLike** [comment]
Any updates on this one @tsterbak? - Should be relatively easy to set up! :smile:

**Comment by tsterbak** [comment]
So far, not too many people wanted to send money to the project. So for now, I would spend the time to set this up elsewhere.
Do you think this would increase donations?

**Comment by MagicLike** [comment]
> Do you think this would increase donations?

Not necessarily, but it would give users a new option to donate. Maybe you should "advertise" on Masto, that OAI happily accepts donations.

**Comment by tsterbak** [comment]
> Not necessarily, but it would give users a new option to donate. Maybe you should "advertise" on Masto, that OAI happily accepts donations.

That makes sense. Probably also add an "Donate now" Button to the last step of the installer.
