### ISSUE TITLE
Is it possible to show views without a device? / Testing mode

### ISSUE THREAD

**Issue by MagicLike** [openandroidinstaller-dev/openandroidinstaller#109]
When editing the individual views, is there a possibility to view those "pages" compiled without a device connected? If not a sort of debug / testing mode would be nice.

**Comment by tsterbak** [comment]
You can get that by running `poetry run python openandroidinstaller/openandroidinstaller.py --test --test_config <device-code>`.

**Comment by MagicLike** [comment]
Will have a look into it!

**Comment by MagicLike** [comment]
Works perfectly fine!
