### ISSUE TITLE
Where are the icons of the header actions stored?

### ISSUE THREAD

**Issue by MagicLike** [openandroidinstaller-dev/openandroidinstaller#112]
I try to optimise some stuff related to my issues and therefore want to add another button to the header. Where can I get / store an icon for my action?

**Comment by tsterbak** [comment]
Buttons for the header are created here: https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/main/openandroidinstaller/openandroidinstaller.py#L238
The icons are the build-in flet icons, which can be found here by searching the icon browser: https://gallery.flet.dev/icons-browser/
