### ISSUE TITLE
Add `Recovery is already flashed` toggle

### ISSUE THREAD

**Issue by MagicLike** [openandroidinstaller-dev/openandroidinstaller#141]
**Is your feature request related to a problem? Please describe.**
Samsung devices which are already flashed with TWRP have to be flashed every time OAI is used to install a ROM.

**Describe the solution you'd like**
It would be great to have a `Recovery is already flashed` toggle at the beginning, just under the `Bootloader is already unlocked`toggle for Samsung devices to skip TWRP flashing.

**Comment by tsterbak** [comment]
This is similar to #88.
Adding an advanced mode to expose kind of features to users seems to be the way to go.

**Comment by tsterbak** [comment]
Added in release 0.4.5.
