### ISSUE TITLE
Logfile is not accessible when using the flatpak version

### ISSUE THREAD

**Issue by tsterbak** [openandroidinstaller-dev/openandroidinstaller#157]
**Describe the bug**
In the flatpak version, there is no way currently to get the log file.

**Expected behavior**
The log file should be somewhere, probably just in home or so.

**Log file**
Please attach the log file. You can find the file in the same directory like the installer executable.
(You might want to clean up some personal information from the file)

**Screenshots**

**Desktop (please complete the following information):**
 - Version 0.4.2 as flatpak

**Comment by tsterbak** [comment]
Currently the applications writes the logs to the directory the executable is started from. This does not work for the flatpak.

@axtloss Is there a way to expose or write a file to a place outside the sandbox of the flatpak? How is it done best? Maybe you have an idea :)

**Comment by axtloss** [comment]
There are two ways of doing this:
1. The log gets written into `~/.var/app/org.openandroidinstaller.OpenAndroidInstaller/data/`, this path is accessable with no restrictions both inside and outside the flatpak
2. I give the flatpak write permission to `~/Documents` (or a different directory in the host) and OpenAndroidInstaller writes the log in there
3. This would probably require a change in the OpenAndroidInstaller code, but it could be an option to save the log, which opens a file selector using the file selection portal, which would allow OpenAndroidInstaller to write the log to whatever path the user sets using the file selector

The simplest solution would be the first one, the best one however would be the third option.
But I could also understand if you'd prefer the second option to improve user experience without a lot of code changes.

**Comment by tsterbak** [comment]
Thanks for your very quick answer! :)

You are right, in the mid/longterm it should be option 3. For now, option 1 would be fine.

**Comment by tsterbak** [comment]
For me, there is nothing written to `~/.var/app/org.openandroidinstaller.OpenAndroidInstaller/data/`. What could go wrong there? :thinking:

**Comment by tsterbak** [comment]
At the moment, the python application just writes to log file `openandroidinstaller.log` to the path the application is started from. Should this be written to a different path, or made more flexible?
Updating the manifest should be fine, I guess :)

**Comment by axtloss** [comment]
> At the moment, the python application just writes to log file `openandroidinstaller.log` to the path the application is started from. Should this be written to a different path, or made more flexible?
> Updating the manifest should be fine, I guess :)

The best option would be if you could make it possible to change the log location using a start argument or an environment variable. Otherwise I'd have to include a patch that changes the hardcoded path, which should be avoided if possible

**Comment by tsterbak** [comment]
> The best option would be if you could make it possible to change the log location using a start argument or an environment variable. Otherwise I'd have to include a patch that changes the hardcoded path, which should be avoided if possible

That makes sense. I will make the necessary changes.
To apply this to the flatpak, does it need a new release, or can flathub just take the code from `main`? Either way, there is a new release planed soon.

**Comment by axtloss** [comment]
> > The best option would be if you could make it possible to change the log location using a start argument or an environment variable. Otherwise I'd have to include a patch that changes the hardcoded path, which should be avoided if possible
> 
> That makes sense. I will make the necessary changes.
> To apply this to the flatpak, does it need a new release, or can flathub just take the code from `main`? Either way, there is a new release planed soon.

Yes a new release would be required

**Comment by axtloss** [comment]
> > The best option would be if you could make it possible to change the log location using a start argument or an environment variable. Otherwise I'd have to include a patch that changes the hardcoded path, which should be avoided if possible
> 
> That makes sense. I will make the necessary changes.
> To apply this to the flatpak, does it need a new release, or can flathub just take the code from `main`? Either way, there is a new release planed soon.

Yes a new release would be required

**Comment by axtloss** [comment]
> > The best option would be if you could make it possible to change the log location using a start argument or an environment variable. Otherwise I'd have to include a patch that changes the hardcoded path, which should be avoided if possible
> 
> That makes sense. I will make the necessary changes.
> To apply this to the flatpak, does it need a new release, or can flathub just take the code from `main`? Either way, there is a new release planed soon.

Yes a new release would be required

**Comment by tsterbak** [comment]
> Yes a new release would be required

Okay, then I come back to this once a release is ready. I guess I go for the start argument option.

**Comment by axtloss** [comment]
> > Yes a new release would be required
> 
> Okay, then I come back to this once a release is ready. I guess I go for the start argument option.

Alright great, I'll update the flatpak once it's ready

also sorry about the duplicated comments, I'm not sure what GitHub did there

**Comment by tsterbak** [comment]
> Alright great, I'll update the flatpak once it's ready

Perfect! Thanks a lot already! :)

> also sorry about the duplicated comments, I'm not sure what GitHub did there

No worries, I though so. I just deleted them :)

**Comment by sudwhiwdh** [comment]
I would be in favour of a solution that doesn't make more holes in the sandbox than necessary and instead clearly and understandably explains to users where they can find the log file that can help you to fix bugs.

**Comment by tsterbak** [comment]
This is resolved with the latest release 0.3.4-beta.
