### ISSUE TITLE
[Dumpling] Fail after Sideload ROM  ( TWRP lock issue ? ) 

### ISSUE THREAD

**Issue by freechelmi** [openandroidinstaller-dev/openandroidinstaller#159]
**Describe the bug**
Got and error after side load because twrp adb was not answering it seems

**To Reproduce**
1. Go to the flashing step where TWRP is booted and start sideload
2. it seems if twrp relock it self 
3. the next action ( wipe cache ? ) after sideload will fail
![Screenshot from 2023-05-16 13-51-51](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/446021/35b97986-58de-45b1-9605-08cebae7aa13)

**Expected behavior**
if I keep unlocking the twrp screen it succeed 

![Screenshot from 2023-05-16 13-54-42](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/446021/5bfc31fa-323e-43be-b72e-5243b33d6e8e)

**Log file**
Please attach the log file. You can find the file in the same directory like the installer executable.
(You might want to clean up some personal information from the file)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Flatpak 
 - Version 0.4.2

**Smartphone (please complete the following information):**
 - Device: One plus 5T dumpling
 - OS: stock
 - Version 10.0.1

**Additional context**

**Comment by MagicLike** [comment]
Please attach the logfile, so others can better understand what happened.

**Comment by tsterbak** [comment]
> Please attach the logfile, so others can better understand what happened.

There is currently an issue with the logfile not being accessible in the flatpak. This will be fixed in the next release.
So everything is alright here :)

**Comment by freechelmi** [comment]
Thanks for the feedback
I tried again with lock disabled in TWRP options and it did not fail 

BUT the final wiper dalvik said " no emulators found" , but as adb reboot worked , I would say it is OK !

**Comment by SirRGB** [comment]
> That's an odd issue. Thanks a lot for reporting it! :)
> 
> Do you think it could be related to the installer trying to wipe to fast after sideloading, but TWRP is not ready yet? Then it could probably wait until the recovery becomes available before trying to wipe. Otherwise I have to figure out a way to keep TWRP from locking.
> 
> @SirRGB can you by any chance reproduce this issue? Maybe you have an idea how to solve it?

Sorry, it has been a while since I posted stuff here, but anyways...
I couldnt replicate the issue on cheeseburger when flashing crdroid 9.7 + fdroid using twrp-3.7.0_12-1-cheeseburger_dumpling.img, so it might be an issue with the twrp you used?

**Comment by freechelmi** [comment]
I also use twrp-3.7.0_12-1-cheeseburger_dumpling.img

I will receive dumpling to day to test again with 0.5.1

**Comment by freechelmi** [comment]
For the record , flashing on samsung note 9 does behave correctly 

```
>Total xfer: 0.98x
>$adb shell twrp wipe dalvik
>Wiping Cache & Dalvik...
>-- Dalvik Cache Directories Wipe Complete!
>Done processing script file
>$adb shell twrp wipe cache
>Formatting Cache using mke2fs...
>Done.
>Done processing script file
>$adb wait-for-recovery
>$adb reboot
```
