### ISSUE TITLE
Documentation data transfer USB Android 12+

### ISSUE THREAD

**Issue by firefoxlover** [openandroidinstaller-dev/openandroidinstaller#164]
Great App! I will try to do a pull request when I have time.

On Android 12+ or so you need to activate "data transfer" in the connection settings, otherwise you cant connect through USB. This will be not very clear, as your device is visible but not accessible.

**Comment by tsterbak** [comment]
Thank you for raising this issue! :)

**Comment by tsterbak** [comment]
@MagicLike If you are looking for something to contribute in the application, this would be a nice one to contribute for the coming release :) Otherwise I will add that just before the release.

**Comment by tsterbak** [comment]
Is fixed in release 0.4.4.

**Comment by MagicLike** [comment]
> @MagicLike If you are looking for something to contribute in the application, this would be a nice one to contribute for the coming release :) Otherwise I will add that just before the release.

Oh sorry, I missed that...
