### ISSUE TITLE
Galaxy S10+ recognized as “beyond2”, setup unable to continue.

### ISSUE THREAD

**Issue by MaravicMarko** [openandroidinstaller-dev/openandroidinstaller#167]
**Describe the bug**

OAI is wrongly/incorrectly recognizing my phone. I have Samsung Galaxy S10+ (Exynos EU version) and its code-name is “beyond2lte”. Yet, by OAI it's recognized as “beyond2” and setup cannot continue. I have enabled USB debugging as well as OEM Unlock.
I have tried setup on two different computers, one with W11 & Fedora (dual boot) and on the other one with Windows 10. All three OSes are fully updated with latest drivers.

**Log file**

[openandroidinstaller.log](https://github.com/openandroidinstaller-dev/openandroidinstaller/files/11579759/openandroidinstaller.log)

**Screenshots**

![OAI_GalaxyS10+_error](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/72248348/d164c269-3725-4b28-95c6-4922674ef34a)

**Desktop (please complete the following information):**

 - OS: Windows 11 22H2, Windows 10 22H2, Fedora Workstation 37 (Flatpack version of OAI)
 - OAI v0.4.2-beta + OAI v0.4.3-beta (on Fedora only v0.4.3-beta)

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy S10+
 - OS: Android 12 
 - Version: One UI 4.1 (March 2023 security patch)

**Comment by tsterbak** [comment]
Hey @MaravicMarko, thanks for reporting the issue :)

You can try if the install works for you device by adapting this config file: https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/main/openandroidinstaller/assets/configs/beyond2lte.yaml
If you add `beyond2` to the list `supported_device_codes` and place the file in the same directory as the executable (does not work for the flatpak). Then it will pickup this config file and recognize the device.
Then we can add support for devices with this device code also.

**Comment by MaravicMarko** [comment]
Hi @tsterbak, thanks for the workaround. I will try it next time I flash new ROM.
Cheers :)

**Comment by MaravicMarko** [comment]
To be honest, I don't know, this was first time I tried OAI. 
So far, I was always using old manual way of Haimdall+adb+TWRP/LineageRecovery etc.
I can try it next weekend, I need phone in working order until then :D

**Comment by tsterbak** [comment]
Great, thanks a lot! Let me know if I can support you in any way :)

**Comment by MaravicMarko** [comment]
Hi @tsterbak sorry for late reply. 

So, I have tried again, but without editing .yaml file, just for test as I had LineageOS flashed in mean time. OAI recognized the phone as "beyond2lte". After that, I flashed with Odin latest official Android 12 firmware and tried again OAI. As last time, the phone was recognized as "beyond2". Then I have tried with editing yaml file as you suggested, but the result was the same :-/
But as I need working Google Pay and banking apps in general, until I get new phone (and current one become test device), I must stay on official firmware.

In any case, thanks for help and your work on OAI.

Best regards,
Marko

**Comment by tsterbak** [comment]
Hi Marko, no worries :) thanks for your reply.
It is very helpful! It seems to be an issue for some devices (especially Samsung), that they change device codes. So I will add support for the device code "beyond2" in the next release (and potentially similarly for more Samsung devices). Thanks a lot!
