### ISSUE TITLE
Make the application window responsive

### ISSUE THREAD

**Issue by sudwhiwdh** [openandroidinstaller-dev/openandroidinstaller#171]
![Screenshot](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/58292468/587c8987-cbb0-4a9d-9cc6-e99df6a8394e)

**Comment by MagicLike** [comment]
In addition to that (Maybe that is included in this request) the "Window" inside the Window showing the actual text content and buttons should also be expanded to the whole window / deleted and the stuff should be moved to the whole window.

**Comment by tsterbak** [comment]
I now set the min width/height for the window. This resolves the issue in a way that you obviously cannot make the window smaller so no responsiveness issues appear.
Would you consider that a reasonable solution?

**Comment by MagicLike** [comment]
> I now set the min width/height for the window. This resolves the issue in a way that you obviously cannot make the window smaller so no responsiveness issues appear.
> Would you consider that a reasonable solution?

Uhhm it seems like the min size does not always apply...

1st opening min size:
![grafik](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/82117109/16e98201-98e1-468e-9a83-c9b50fdb224b)

after window snapping and then residing:
![grafik](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/82117109/d2b46f36-4ee1-4ba1-8ba8-b60c2837a9c4)


Also I noticed, that the buttons are now narrower, the title font size has reduced and the toggles have a different style:
| before | after |
| --- | --- |
| ![grafik](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/82117109/e5bfc0dd-7c1c-4266-ae5d-6fb29a7c8dcf) | ![grafik](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/82117109/73d265fa-263d-4b15-a959-0063c8aa96c8) |
| ![grafik](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/82117109/f138810b-6dde-49e9-ae38-b41481667692) | ![grafik](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/82117109/9f37ee77-6583-48bd-babe-8ae5ae0d913c) |
| ![grafik](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/82117109/0f56e8dc-de59-4dfe-a313-c366856bb1d4) | ![grafik](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/82117109/5d836c33-7cdd-467d-930c-5373fa825bed) |
| ![grafik](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/82117109/c692946b-13a8-4299-84f0-a173bd5cdc72) | ![grafik](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/82117109/1b0ed9fc-1c81-4d14-b581-51288d120040) |

**Comment by MagicLike** [comment]
> Thanks for testing it so fast!

Np! :heart: 

> Yeah, I update flet (the library that is used to build the application) and they changed their style a bit. I think I also like it.

Yup, looks neat indeed!

**Comment by tsterbak** [comment]
Will be released with release 0.4.4
