### ISSUE TITLE
Failed to load config for samsung j7 prime

### ISSUE THREAD

**Issue by linhcentrio** [openandroidinstaller-dev/openandroidinstaller#173]
![image](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/45778128/199055f9-3e5a-4acf-b063-6eb388fd5a23)

**Comment by tsterbak** [comment]
Hi, thanks for trying the tool :)
Currently this device is not supported by the installer. It should be easy to extend the installer to support it, so far there was no one to test it. Would you want to contribute a config, test and add it? I can help you along the way :)
You can find more details here: https://github.com/openandroidinstaller-dev/openandroidinstaller#how-to-contribute-your-own-installation-configurations And it should be easy to start off an existing config for a samsung device.

**Comment by MagicLike** [comment]
PR open at #209!

@linhcentrio please test the config on your end.
