### ISSUE TITLE
Check whether the installer can be used to install DivestOS reliably

### ISSUE THREAD

**Issue by sudwhiwdh** [openandroidinstaller-dev/openandroidinstaller#176]
It looks like it is privacy friendly and provides increased security: https://www.kuketz-blog.de/divestos-datenschutzfreundlich-und-erhoehte-sicherheit-custom-roms-teil5/

Here you will find the manual installation instructions for DivestOS: https://divestos.org/pages/bootloader
and a list of supported devices: https://divestos.org/pages/devices

The developer of DivestOS writes that it might need additional steps for Verified Boot, relocking the bootloader and handling the firmware.

**Comment by freechelmi** [comment]
I don't think the app will guide you for bootloader relock , but for all the steps before , divest is just a lineageos

**Comment by tsterbak** [comment]
So far, I haven't tried it since I don't own a supported device. If you want to try it and report if it works, as @freechelmi said, it should most likely work.

Relocking the bootloader is not supported by the openandroidinstaller yet, but it is on the low priority backlog. Since it is rather risky or impossible to relock the bootloader for most devices and can easily result in a hard brick, I currently don't see it coming soon.

**Comment by anon1892** [comment]
Installing DivestOS works fine, this is the ROM with which I tested my lavender (Redmi Note 7) configuration file.
To be precise : I installed DivestOS with OrangeFox and not with the fastboot method, as mentioned on the DivestOS website. But works fine (and anyway, we cannot lock lavender bootloader)

**Comment by MagicLike** [comment]
I also tried it on the OnePlus One - works like a charm!

**Comment by MagicLike** [comment]
> I do NOT recommend TWRP due to its included malware app & partnership: https://twrp.me/app/privacypolicy.pdf
> 
> > Location information (e. g. longitude / latitude)
> > Usage information (e. g. transferred amount of data, call logs)
> > App usage (e. g. of all installed apps, their usage time, duration, volume and location)

Did not know about the app privacy - but I have never used it anyway. :D

**Comment by tsterbak** [comment]
> Use of alternative recoveries are also not supported and not recommended.
They cannot handle the encryption changes and none of them pin the key for verification purposes.

> I do NOT recommend TWRP due to its included malware app & partnership:
https://twrp.me/app/privacypolicy.pdf

Sadly TWRP (and OrangeFox catching up) seem to be the only recoveries providing a somewhat usable support for scripting (as far as I know). This makes it easier to run the installation process.
