### ISSUE TITLE
Samsung Galaxy S10 

### ISSUE THREAD

**Issue by oti4500** [openandroidinstaller-dev/openandroidinstaller#178]
**Device name**
Samsung Galaxy S10
SM-G973F
beyond1

**Device images**
LineageOS: https://download.lineageos.org/devices/beyond1lte/builds

**Do you own the device and would be willing to test the installer?**
- [ yes ]

**Additional context**
I don't find any other custom rom.

**Comment by tsterbak** [comment]
Hi @oti4500,
this device should already be supported. Have you tested the installer with the device?
I'm happy to assist if something goes wrong or is unclear.
Let me know how it goes :)

**Comment by MagicLike** [comment]
> Hi @oti4500, this device should already be supported. Have you tested the installer with the device? I'm happy to assist if something goes wrong or is unclear. Let me know how it goes :)

fixed in #205

**Comment by tsterbak** [comment]
Merged and will be released in version 0.4.5-beta.
