### ISSUE TITLE
Install OS progress goes to 100% but need more time to complete

### ISSUE THREAD

**Issue by nicorikken** [openandroidinstaller-dev/openandroidinstaller#181]
**Describe the bug**
Install OS step has a progress indicator going to 100%
You get to a point where the progress bar is at 100% without the user being able to continue and with no progress spinner. The UI seems frozen to the user whereas the user has to wait a little bit longer.

**To Reproduce**
1. Go to install os
2. Wait until 100%
3. See no option yet to continue 
4. See no other indicator of activity 

**Expected behavior**
Either keep progress bar at 99% or something until able to continue, or change to a spinner once bar is at 100%. As to have a visual clue to wait.

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Version 0.4.3-beta

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: LineageOS

**Additional context**
-

**Comment by tsterbak** [comment]
Should be resolved in the next release 0.4.5-beta.
