### ISSUE TITLE
Flatpak Version not Working

### ISSUE THREAD

**Issue by larus-argentatus-sec** [openandroidinstaller-dev/openandroidinstaller#189]
**Describe the bug**
I cannot run the Flatpak Version of the Application

**To Reproduce**
1. Open Terminal
2. Run `flatpak install flathub org.openandroidinstaller.OpenAndroidInstaller`
3. Accept Installation
4. Run `flatpak run org.openandroidinstaller.OpenAndroidInstaller`
5. See error (aka nothing happens)

**Expected behavior**
The app should open

**Log**
`Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/openandroidinstaller/openandroidinstaller.py", line 45, in <module>
    from views import (
  File "/app/lib/python3.10/site-packages/openandroidinstaller/views/__init__.py", line 3, in <module>
    from .start_view import StartView  # noqa
  File "/app/lib/python3.10/site-packages/openandroidinstaller/views/start_view.py", line 34, in <module>
    from flet_core.buttons import CountinuosRectangleBorder
ModuleNotFoundError: No module named 'flet_core'`

**Desktop**
 - OS: Fedora SIlverblue
 - Version: 38

**Comment by tsterbak** [comment]
Hey, thank you for reporting the issue.
Can you please try to update the flatpak? The fix for this issue should have been out around two hours ago.

Please let me know if it works for you. Otherwise I need to see that I find a fix.

**Comment by Heus-Sueh** [comment]
> Hey, thank you for reporting the issue. Can you please try to reinstall the flatpak? The fix for this issue should have been out around two hours ago.
> 
> Please let me know if it works for you. Otherwise I need to see that I find a fix.

now it works again
