### ISSUE TITLE
Add support for jfltetmo

### ISSUE THREAD

**Issue by keith101786** [openandroidinstaller-dev/openandroidinstaller#196]
@**Device name**
Please enter the name of the device you would like to request support for.
If you know the device code, please also add it here.

**Device images**
Please provide links to any available images of the device, such as official stock firmware or custom ROMs you would like to install.

**Do you own the device and would be willing to test the installer?**
- [ ]

**Additional context**
Please provide any additional context or information that may be helpful in adding support for this device.

**Comment by tsterbak** [comment]
Thanks for your request. 

This should be relatively easy to add.
https://wiki.lineageos.org/devices/jfltexx/install

Follow the steps here: https://github.com/openandroidinstaller-dev/openandroidinstaller#how-to-contribute-your-own-installation-configurations to create a config file for this device. It should be quite similar to this one https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/main/openandroidinstaller/assets/configs/serranoltexx.yaml 

Then you can test it with the installer and if it works for you, please open a PR in this repo :)

**Comment by MagicLike** [comment]
@tsterbak What device code should be used as the main one? `jfltetmo`or `jfltexx`?

**Comment by MagicLike** [comment]
nvm I just did a little search and found out, that `jfltetmo` is just the t-mobile version and therefore I will add `jfltexx` as the main code and `jfltetmo` as a supported code!

**Comment by MagicLike** [comment]
PR is open at #207! @keith101786 If you need any further help with testing, just ask! :heart:

**Comment by keith101786** [comment]
Jflte
