### ISSUE TITLE
Add support for a5y17ltecan

### ISSUE THREAD

**Issue by CanadaMan150** [openandroidinstaller-dev/openandroidinstaller#203]
**Samsung A5 2017 (a5y17ltecan) **

**Device images**
I dont know if this counts since its not a fork of android but
https://files.kde.org/neon/images/mobile/20230125-0250/

**Do you own the device and would be willing to test the installer?**
- [yes i do own the devie and am willing to test the installer ]

**Additional context**
Samsung A5 2017 is allready supported, but its the (a5y17lte) vertion and not the (a5y17ltecan) vertion

**Comment by MagicLike** [comment]
Afaik this should be an easy fix, as OAI supports adding multiple device codes to one phone. Is the Canadian version different in terms of hardware?

**Comment by MagicLike** [comment]
It does not seem like it...

**Comment by MagicLike** [comment]
PR is now open at #206 

If this is a urgent fix for you @CanadaMan150, I can walk you through how to apply the fix for you locally, until the next OAI update is released.

**Comment by CanadaMan150** [comment]
sorry for the long wait, timezones and such

im ok to wait for the next update since its not to urgent of a fix
thank you

also, the image that i provided, would that count as a usable, android is built off of the linux kernel but changed arround a bit, but idk if the amount of changes would break it to much to not be able to work like changing an android ROM

**Comment by MagicLike** [comment]
> also, the image that i provided, would that count as a usable, android is built off of the linux kernel but changed arround a bit, but idk if the amount of changes would break it to much to not be able to work like changing an android ROM

Uhhm I don't know... I never tried flashing Linux ISOs via OAI, especially as Android devices have a different partitioning and structure, I don't think it would be possible atm. Maybe you should consider looking into kde's documentation about it.

**Comment by MagicLike** [comment]
Also OAI does not accept ISO files to be used as image (only zips which contain the .img files)
