### ISSUE TITLE
Add support for beyond0

### ISSUE THREAD

**Issue by robro69** [openandroidinstaller-dev/openandroidinstaller#204]
**Device name**
Please enter the name of the device you would like to request support for.
If you know the device code, please also add it here.
Samsung Galaxy S10e (exynos)
SM-G970F/DS

**Device images**
Please provide links to any available images of the device, such as official stock firmware or custom ROMs you would like to install.
https://doc.e.foundation/devices/beyond0lte

**Do you own the device and would be willing to test the installer?**
- [ ] Yes I own the device and I'm willing to test the installer.

**Additional context**
Please provide any additional context or information that may be helpful in adding support for this device.

**Comment by MagicLike** [comment]
The device is actually already supported, but it seems that your's is spitting out another device code. Should be easy to fix! :smiley:

**Comment by MagicLike** [comment]
PR is open at #205 - should be fixed in the next update!

Is the fix urgent for you @robro69? If so, I can walk you through fixing it for yourself locally, instead of waiting for an update...

**Comment by robro69** [comment]
> PR is open at #205 - should be fixed in the next update!
> 
> Is the fix urgent for you @robro69? If so, I can walk you through fixing it for yourself locally, instead of waiting for an update...

Great news! No, it's not urgent at all. I`ll wait for an update. ;-)

**Comment by tsterbak** [comment]
Merged and will be released in version 0.4.5-beta.

**Comment by robro69** [comment]
Great news! Thank you ever so much.

Kind regards
Roland

Skickat från ProtonMail mobile

-------- Originalmeddelande --------
Den 22 aug. 2023 10:23, Tobias Sterbak skrev:
