### ISSUE TITLE
Add support for raphael

### ISSUE THREAD

**Issue by alkman1982** [openandroidinstaller-dev/openandroidinstaller#212]
**Device name**
Please enter the name of the device you would like to request support for.
If you know the device code, please also add it here.

**Device images**
Please provide links to any available images of the device, such as official stock firmware or custom ROMs you would like to install.

**Do you own the device and would be willing to test the installer?**
- [ ]

**Additional context**
Please provide any additional context or information that may be helpful in adding support for this device.

**Comment by MagicLike** [comment]
Currently not possible, see #188, #218 & #221 

Example PR: #222

**Comment by MagicLike** [comment]
tagging @anon1892

**Comment by anon1892** [comment]
Done. @alkman1982 do you want to test it ?

**Comment by MagicLike** [comment]
Support added in v0.5.0 - but still needs testing
