### ISSUE TITLE
Add support for davinci

### ISSUE THREAD

**Issue by Chronos093** [openandroidinstaller-dev/openandroidinstaller#232]
**Device name**
Please enter the name of the device you would like to request support for.
If you know the device code, please also add it here.

**Device images**
Please provide links to any available images of the device, such as official stock firmware or custom ROMs you would like to install.

**Do you own the device and would be willing to test the installer?**
- [ ]

**Additional context**
Please provide any additional context or information that may be helpful in adding support for this device.

**Comment by anon1892** [comment]
https://wiki.lineageos.org/devices/davinci/install/variant1
Seems very similar to #222, I can do that today

**Comment by anon1892** [comment]
Done. 
@Chronos093 Would you help us by testing it ? See #234

**Comment by tsterbak** [comment]
Has been released with 0.5.0.
