### ISSUE TITLE
Maybe use issue forms for templates

### ISSUE THREAD

**Issue by MagicLike** [openandroidinstaller-dev/openandroidinstaller#242]
**Is your feature request related to a problem? Please describe.**
Many issue templates are left blank (especially for device requests) probably, because not so tech savy people are hit with a markdown field they have to edit.

**Describe the solution you'd like**
Introduce the use of [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)

**Describe alternatives you've considered**
Asking the people who make requests manually to complete the information, but almost never there is a response.

**Additional context**
I can take a look into converting the current template(s) into forms.

**Comment by tsterbak** [comment]
Awesome idea! I didn't know this feature of github 😊

**Comment by MagicLike** [comment]
> Awesome idea! I didn't know this feature of github blush

The form can be seen in action here: https://github.com/Magic-Tests/issue-forms/issues
Should I change anything? Should any other templates be reworked atm?

**Comment by anon1892** [comment]
Wow, good job! We may start with this one, and if needed, adapt others templates too, what do you think? (others aren't used a lot by newcomers)

**Comment by MagicLike** [comment]
> Wow, good job! We may start with this one, and if needed, adapt others templates too, what do you think? (others aren't used a lot by newcomers)

Thanks ^^
I had the same idea - also forms don't really give users the option to submit pictures, which might not be so good for the use in a bug report.
I'm gonna open a PR now!
