### ISSUE TITLE
Add support for Cubot QUEST

### ISSUE THREAD

**Issue by BlackMistery** [openandroidinstaller-dev/openandroidinstaller#244]
**Device informations**
- Brand:  None
- Phone name: Cubot Quest
- Device code (if unknown, leave blank): 
- Model (if several models exist):  Cubot Quest

**Device images**  
Please provide links to any available images of the device, such as official stock firmware or custom ROMs you would like to install.  

**Do you own the device and would be willing to test the installer?**
- [ ]

**Additional context**  
Please provide any additional context or information that may be helpful in adding support for this device.

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell.

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell.
