### ISSUE TITLE
Add support for Telma_F1_Max_4G

### ISSUE THREAD

**Issue by RomualdSandamalala2002** [openandroidinstaller-dev/openandroidinstaller#257]
**Device informations**
- Brand: Telma
- Phone name: F1 Max 4G
- Device code (if unknown, leave blank): 
- Model (if several models exist): 

**Device images**  
Please provide links to any available images of the device, such as official stock firmware or custom ROMs you would like to install.  

**Do you own the device and would be willing to test the installer?**
- [ Yes]

**Additional context**  
Please provide any additional context or information that may be helpful in adding support for this device.

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell.
