### ISSUE TITLE
Add support for mocha

### ISSUE THREAD

**Issue by gothikj** [openandroidinstaller-dev/openandroidinstaller#262]
**Device informations**
- Brand: Xiaomi
- Phone name: MIPAD 1 (2015)
- Device code (if unknown, leave blank): Mocha
- Model (if several models exist): MI PAD 1

**Device images**  
Please provide links to any available images of the device, such as official stock firmware or custom ROMs you would like to install.  

https://miuirom.org/tablets/mi-pad-1

**Do you own the device and would be willing to test the installer?**
- [YES ]

**Additional context**  
Please provide any additional context or information that may be helpful in adding support for this device.

**Comment by MagicLike** [comment]
tagging @anon1892

**Comment by anon1892** [comment]
Install process seems strange, never saw this before.
https://forum.xda-developers.com/t/lineageos-16-0-19-04-2020-shield-blobs.4015965/

Furthermore, will need changes in OAI, for `tos`... And it seems to be a hack, due to lack of space on a partition...

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
