### ISSUE TITLE
Add support for PocoF3 alioth

### ISSUE THREAD

**Issue by Emerosn** [openandroidinstaller-dev/openandroidinstaller#275]
**Device informations**
- Brand: Xiaomi
- Phone name: PocoF3
- Device code (if unknown, leave blank): 
- Model (if several models exist): TKHMIXM

**Device images**  
Please provide links to any available images of the device, such as official stock firmware or custom ROMs you would like to install.
https://download.lineageos.org/devices/alioth/builds

**Do you own the device and would be willing to test the installer?**
- [ yes ]

**Additional context**  
Please provide any additional context or information that may be helpful in adding support for this device.

I only use Linux and the unlocked boot loader is only available for Windows.

**Comment by MagicLike** [comment]
tagging @anon1892

**Comment by anon1892** [comment]
It needs a new command for `fastboot flash vendor_boot vendor_boot.img` (so addition in #246 )
Else, seems similar to #225

**Comment by tsterbak** [comment]
> It needs a new command for fastboot flash vendor_boot vendor_boot.img (so addition in https://github.com/openandroidinstaller-dev/openandroidinstaller/pull/246 )

Yes, I guess this will be an easy extension for a later release.

**Comment by tsterbak** [comment]
`fastboot flash vendor_boot vendor_boot.img` is now implemented in #317 . So development here can continue.

**Comment by anon1892** [comment]
May want you test it @Emerosn?

It's not tested, and `vendor_boot` has never been tested. Otherwise, it's based on a tested working config, so I'm pretty confident.

**Comment by MagicLike** [comment]
Implemented in [v0.5.1-beta](https://github.com/openandroidinstaller-dev/openandroidinstaller/releases/tag/v0.5.1-beta)
