### ISSUE TITLE
Add support for Y3

### ISSUE THREAD

**Issue by Nyneve1** [openandroidinstaller-dev/openandroidinstaller#281]
**Device informations** Yotaphone 
- Brand: 
- Phone name: 
- Device code (if unknown, leave blank): 
- Model (if several models exist): Yota 3 Dual-Display
- Android 7.11
-Baseband-Version: 8953_GEN_PACK_-1.102097.1.104384.

**Device images**  
Please provide links to any available images of the device, such as official stock firmware or custom ROMs you would like to install.  

Hisense A2 
or any other firmware 

**Do you own the device and would be willing to test the installer?**
- [ yes]

**Additional context**  
Please provide any additional context or information that may be helpful in adding support for this device.  

https://www.devicespecifications.com/en/model/83f54541

https://www.gsmarena.com/yota_yotaphone_3-8727.php

**Comment by SirRGB** [comment]
Seems like a pretty niche device to me. Are there any custom roms, that could be flashed using oai? The only thing I found so far were a thread about twrp, but all links were dead.
I dont own this device btw, just dug around...

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell.
