### ISSUE TITLE
Add support for cupid

### ISSUE THREAD

**Issue by RedAuburn** [openandroidinstaller-dev/openandroidinstaller#285]
**Device information**
- Brand: Xiaomi
- Phone name: 12
- Device code (if unknown, leave blank): 
- Model (if several models exist): 

**Device images**  
- LineageOS 20: https://forum.xda-developers.com/t/rom-13-unofficial-lineageos-20-for-xiaomi-12.4586861/

**Do you own the device and would be willing to test the installer?**
- yes

**Comment by anon1892** [comment]
See #287

**Comment by MagicLike** [comment]
Support added in v0.5.0

**Comment by RedAuburn** [comment]
i no longer own a x12 so am unable to test unfortunately :(
