### ISSUE TITLE
Add support for ML-JI08-M7S-PLUS

### ISSUE THREAD

**Issue by JackInsahnus** [openandroidinstaller-dev/openandroidinstaller#289]
**Device informations**
- Brand: Multilaser
- Phone name: M7S Plus
- Device code (if unknown, leave blank): 
- Model (if several models exist): ML-JI08

**Device images**  
Please provide links to any available images of the device, such as official stock firmware or custom ROMs you would like to install.

https://www.multilaser.com.br/tablet-multilaser-m7s-plus-wi-fi-7-pol-16gb-android-81-quad-core-azul-nb299/p

**Do you own the device and would be willing to test the installer?**
- [ ]Any Linux System

**Additional context**  
Please provide any additional context or information that may be helpful in adding support for this device.

**Comment by MagicLike** [comment]
Thank you for your interest in OAI!
`ML-JI08-M7S-PLUS` does not seem to be a device code. Can you elaborate on that?
I checked the website you linked, but I was not able to find any flashable images - maybe its also my bad Portuguese... :D
If I have overlooked something, please tell me!
Also please confirm, that you are in possession of the device and are willing to test the config.

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell.
