### ISSUE TITLE
Add support for ML_SO0F_M8_WIFI

### ISSUE THREAD

**Issue by sh-jmb** [openandroidinstaller-dev/openandroidinstaller#294]
**Device informations**
- Brand:  Multilazer
- Phone name: M8_WIFI
- Device code (if unknown, leave blank): 
- Model (if several models exist): ML_SO0F_M8_WIFI.V5_20220812

**Device images**  
Please provide links to any available images of the device, such as official stock firmware or custom ROMs you would like to install.  

https://lineageos.org/
https://resurrectionremix.com/

**Do you own the device and would be willing to test the installer?**
- Yes

**Additional context**  
Please provide any additional context or information that may be helpful in adding support for this device.  
I have no additional information

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell.
