### ISSUE TITLE
Add support for beyond1

### ISSUE THREAD

**Issue by changenowde** [openandroidinstaller-dev/openandroidinstaller#297]
**Device informations**
- Brand: Samsung
- Phone name: Galaxy S10
- Device code (if unknown, leave blank): SM-G973F/DS
- Model (if several models exist): S10 without + or e or anything ;-)

**Device images**  
Please provide links to any available images of the device, such as official stock firmware or custom ROMs you would like to install.

I would like to install /e/os with fdroid  

**Do you own the device and would be willing to test the installer?**
- Yes and yes. :-)

**Additional context**  

I thought the S10 was supported, but the software does not recognize it as beyond1lte - but only as beyond1 - without anything behind it. Maybe this is an easy addition? As it seems that just the name that is different. 

Thanks and greetings, 

André

**Comment by MagicLike** [comment]
Already fixed in #205 - Will get released with the next update. If it is urgent for you, I can walk you through on how to apply the fix locally...
