### ISSUE TITLE
Show warning to use the device normally once if needed

### ISSUE THREAD

**Issue by MagicLike** [openandroidinstaller-dev/openandroidinstaller#307]
**Is your feature request related to a problem? Please describe.**
As seen in among others the [Pixel 7 Lineage installation guide](https://wiki.lineageos.org/devices/panther/install#basic-requirements)
![grafik](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/82117109/83566e4c-5d8a-485d-92e8-713523abe4f6)

**Describe the solution you'd like**
Add a warning via metadata to certain configs or make it a general checkmark before starting with the installation (next to battery is charged, etc.)

**Comment by anon1892** [comment]
Can be done with `brand` or just with `notes` metadata, isn't it?

**Comment by tsterbak** [comment]
I would probably add it to the requirements section.
