### ISSUE TITLE
Add support for `begonia`

### ISSUE THREAD

**Issue by branco2552** [openandroidinstaller-dev/openandroidinstaller#309]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Xiaomi

### Name

Xiaomi Redmi Note 8 Pro

### Device code

begonia

### Model

M01906G7G

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Please see #310 

Do you know how to test it?

**Comment by MagicLike** [comment]
Hey there @branco2552! As you might have seen, the PR for your device has already been merged and support for the Redmi Note 8 Pro will be added in the next update. Would you mind testing it now, so we can be sure the config works?

**Comment by tsterbak** [comment]
Merged and officially still untested.
