### ISSUE TITLE
Add support for `WVR_sprout`

### ISSUE THREAD

**Issue by Dev-Nish** [openandroidinstaller-dev/openandroidinstaller#313]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Nokia

### Name

Nokia 2.4

### Device code

WVR_sprout

### Model

2.4

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell.
