### ISSUE TITLE
Add support for `ellis`

### ISSUE THREAD

**Issue by EZ-302** [openandroidinstaller-dev/openandroidinstaller#314]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Motorola

### Name

Moto G Pure

### Device code

Ellis

### Device images

```Markdown
Factory Rom - https://mirrors.lolinet.com/firmware/motorola/ellis/official/TMO/
Gitlab Rom Dump - https://dumps.tadiphone.dev/dumps/motorola/ellis
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
As of now my phone is rooted but currently no Custom Recovery for my device yet. Any help would be greatly appreciated as I dont quite understand how to compile sources yet. Id be willing to learn if there were somewhere to learn from. Unfortunately there isnt much support for my device.
```

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
