### ISSUE TITLE
Add support for `Odin`

### ISSUE THREAD

**Issue by TechnoTubing** [openandroidinstaller-dev/openandroidinstaller#319]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

TCL

### Name

Tab 10s

### Device code

Odin

### Model

9081X

### Device images

```Markdown
I cannot even find any documentation on it, let alone firmware.
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
It's such an obscure device, that I'd be doubtful if you guys even know of it.
```

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
