### ISSUE TITLE
Add support for `surya`

### ISSUE THREAD

**Issue by S13ND3R** [openandroidinstaller-dev/openandroidinstaller#323]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

POCO

### Name

Poco X3

### Device code

surya

### Model

M2007J20CI

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Can you test it @S13ND3R please?

**Comment by tsterbak** [comment]
Merged and officially still untested.
