### ISSUE TITLE
Issues running on Wayland

### ISSUE THREAD

**Issue by nicorikken** [openandroidinstaller-dev/openandroidinstaller#324]
**Describe the bug**
Flatpak install doesn't start in Wayland session, resulting in Flutter error.

**To Reproduce**
1. Install OpenAndroidInstaller v0.5.0 using Flatpak on Debian 12 bookworm running in default Wayland session.
2. Run using the CLI for more output.
3. See error 'Failed to start Flutter renderer: No GL implementation is available' (slightly different in the Dutch language I'm testing.
4. Switch user session from the login screen (after logging out) to X11 session and see it start just fine.

**Expected behavior**
It also works on Wayland or comes with a configuration to make it work through XWayland.

**Log file**
Please attach the log file. You can find the file in the same directory like the installer executable.
(You might want to clean up some personal information from the file)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 12 Bookworm running Wayland
 - Version 0.5.0

**Comment by tsterbak** [comment]
Hi, thank you for reporting this issue.
I'll look into it, but maybe this is hard to resolve if it's not resolved upstream... I was hoping flatpak prevents these kind of issues.
Do you get the same result if you use the downloaded executable? That would be interesting.

**Comment by RaptaG** [comment]
Hello, I cannot reproduce the issue (Running MX Linux 23.1 with Wayland and OAI from Flathub)

**Comment by nicorikken** [comment]
Today I tried it again on Debian in a Wayland session and it works well. Will close the issue.
