### ISSUE TITLE
Add support for `G0730WW`

### ISSUE THREAD

**Issue by dol0han** [openandroidinstaller-dev/openandroidinstaller#331]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

blu

### Name

g40

### Device code

G0730WW

### Model

g40

### Device images

```Markdown
https://kali.download/nethunter-images/kali-2023.3b/nethunter-2023.3b-generic-arm64-kalifs-full.zip
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
