### ISSUE TITLE
Add support for `OnePlusN200`

### ISSUE THREAD

**Issue by Doomsdayrs** [openandroidinstaller-dev/openandroidinstaller#332]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

OnePlus

### Name

OnePlus N200 5G

### Device code

OnePlusN200

### Model

DE2117

### Device images

```Markdown
- https://wiki.lineageos.org/devices/dre/
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
This seems to be a different device code?
```

**Comment by MagicLike** [comment]
> This seems to be a different device code?

Seems like it - should be a relatively easy fix, but atm I am a bit busy... If it is urgent for you, I can show you how to apply the fix locally...

**Comment by SirRGB** [comment]
OnePlusN200 is on the list for a while now, so is this resolved?

https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/main/openandroidinstaller/assets/configs/dre.yaml#L8

**Comment by Doomsdayrs** [comment]
It is a different device code, thus it doesn't get registered as the same device

**Comment by SirRGB** [comment]
Ah, my bad, misread
So just "OnePlusN200"? Ill add it so u can test.
