### ISSUE TITLE
[PIN ME] Mi Unlock may unlock the bootloader without the time delay

### ISSUE THREAD

**Issue by RaptaG** [openandroidinstaller-dev/openandroidinstaller#333]
I unlock my Redmi Note 9 Pro's bootloader today, without the 7 day gap, and all my data was erased (I had no backups either)

Before you unlock your Mi device, make a backup of your data somewhere outside the phone!!

(I made this issue quickly, there should be a disclaimer somewhere in the README and the website)

I'll do more research and see if other people have encountered this as well

**Comment by anon1892** [comment]
It has nothing to do with Mi Unlock : unlocking the bootloader of all phones and all brands reset the phone (look at the README, first sentence of the “Warning” part, in red
