### ISSUE TITLE
Add support for `dipper`

### ISSUE THREAD

**Issue by maksymx** [openandroidinstaller-dev/openandroidinstaller#335]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Xiaomi

### Name

Mi 8

### Device code

dipper

### Device images

```Markdown
- Official ROM https://bigota.d.miui.com/V11.0.4.0.QEAMIXM/miui_MI8Global_V11.0.4.0.QEAMIXM_5e74c6110e_10.0.zip
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context
Specifications
--
Qualcomm SDM845 Snapdragon 845

6/8 GB LPDDR4X

Octa-core Kryo 3854 x 2.8 GHz + 4 x 1.8 GHz

Qualcomm Adreno 630

**Comment by MagicLike** [comment]
tagging @anon1892

**Comment by anon1892** [comment]
Can you test it @maksymx please?

**Comment by maksymx** [comment]
@anon1892 is there a guide about testing? Or I need just open the app and try to test?

**Comment by anon1892** [comment]
> @anon1892 is there a guide about testing? Or I need just open the app and try to test?

Given your profile picture, you're running Linux (don't know how to do that on Windows)
Download the code associated to #341 : https://github.com/anon1892/oai/archive/refs/heads/dipper.zip

**Comment by anon1892** [comment]
> @anon1892 is there a guide about testing? Or I need just open the app and try to test?

Given your profile picture, you're running Linux (don't know how to do that on Windows)
Download the code associated to #341 : https://github.com/anon1892/oai/archive/refs/heads/dipper.zip
Unzip it, enter the folder and open a terminal. Then, type : 
- `make poetry`
- `make install`
- `make app`

If you want to start again the app, you only need to type the last command.

And tell us what it does !

WARNING : Unlocking your bootloader will factory reset your phone : make sure all data you want to keep is backed up

**Comment by MagicLike** [comment]
> > @anon1892 is there a guide about testing? Or I need just open the app and try to test?
> 
> Given your profile picture, you're running Linux (don't know how to do that on Windows)
> Download the code associated to #341 : https://github.com/anon1892/oai/archive/refs/heads/dipper.zip
> Unzip it, enter the folder and open a terminal. Then, type : 
> - `make poetry`
> - `make install`
> - `make app`
> 
> If you want to start again the app, you only need to type the last command.
> 
> And tell us what it does !
> 
> WARNING : Unlocking your bootloader will factory reset your phone : make sure all data you want to keep is backed up

The other "easier" way is just downloading the config an placing it in the same folder as the executable repective to the platform. OAI will load this config just as it was included.

**Comment by anon1892** [comment]
Oops 🙈

**Comment by SirRGB** [comment]
You can install the flatpak and test that.

**Comment by maksymx** [comment]
hey, sorry for a long answer, was busy.

I've tried to install the lineageOS on my mi8, but after all steps it went into bootloop

**Comment by tsterbak** [comment]
> hey, sorry for a long answer, was busy.

No need to be sorry, that happens to all of us all the time :grin: 

> I've tried to install the lineageOS on my mi8, but after all steps it went into bootloop

Can you upload the log file of the installer here? (How to find the logfile: https://openandroidinstaller.org/faq.html#find-logs)

**Comment by tsterbak** [comment]
Merged and officially still untested.
