### ISSUE TITLE
Add support for `OP5958L1`

### ISSUE THREAD

**Issue by emilyb74** [openandroidinstaller-dev/openandroidinstaller#344]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

OnePlus

### Name

Nord N30

### Device code

OP5958L1

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by keith101786** [comment]
I also own this same device and will test for you
****

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
