### ISSUE TITLE
Add support for `DMTAB` 

### ISSUE THREAD

**Issue by droopilla** [openandroidinstaller-dev/openandroidinstaller#347]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Nabi Dreamtab HD8

### Name

Dreamtab

### Device code

DMTAB

### Model

DMTAB_IN08A

### Device images

```Markdown
https://xdaforums.com/tags/nabi-dreamtab-hd8/
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
As you can see in XDA, there isn't custom ROM for your device... And it is too old to be compatible with GSI.
I think we will not be able to do to anything for you, sorry.

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
