### ISSUE TITLE
Add support for `BV9900Pro`

### ISSUE THREAD

**Issue by scg15** [openandroidinstaller-dev/openandroidinstaller#350]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Blackview

### Name

BV9900Pro

### Device code

?

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Uh, I'm sorry, but your phone will probably never be supported by OpenAndroidInstaller : 
https://xdaforums.com/tags/bv9900pro/
There is no development on it, no recovery, and the camera doesn't work on GSI (according to the only post on XDA)

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
