### ISSUE TITLE
Xiaomi Redmi 7A missing instructions for stock upgrade to android 10

### ISSUE THREAD

**Issue by Gredin67** [openandroidinstaller-dev/openandroidinstaller#352]
Trying to flash a Redmi 7A to /e/OS. Last week no TWRP was available (it came out today https://twrp.me/xiaomi/xiaomi-mi439.html), although the device was marked as supported.
Also, no instructions were provided to upgrade the device to Android 10 (MiUI 12/12.5), although it was said to be linked in the instructions. Which is the recommended way ?

I think it would be better to wait for all devices to be tested in real conditions before adding them to the list of supported devices. Otherwise, there is a risk that e.g. no twrp is available (only recoveries from /e/OS or LineageOS).

I think in this PR a batch was added without testing of all devices.
https://github.com/openandroidinstaller-dev/openandroidinstaller/pull/226/files

**Comment by anon1892** [comment]
Redmi 7A (pine) is one of the phone I have the most tested... At the beginning, it was even working with OrangeFox, but official TWRP was already released when I push this PR. Don't know why you didn't find it last week. It was tested with official Lineage, among others official & unofficial custom ROM... So, what more do you want I test ?

> Also, no instructions were provided to upgrade the device to Android 10 (MiUI 12/12.5)

On which version are you? One way is to use https://xiaomifirmwareupdater.com/miui/pine/, download "fastboot" version (so a .tgz file), then unzip it, they execute `flash_all.sh` or `flash_all.bat` depending on your OS.

The #226 was tested. Untested PR are mentioned as untested.

Even unofficial TWRP usually works, so we can support it. If we're waiting for official support of all ROMs and recoveries, our list will not be long...

Why did you put the "bug" label? You don't even seem to have tested it.

**Comment by Gredin67** [comment]
I've spent more than 6 hours trying to flash the 7A, first time because I did not find the TWRP. Because it was not listed as 7A, but as SDM439 Devices https://twrp.me/Devices/Xiaomi/ And as it was all fresh, it was not indexed in the search engines.

And second time because I could not manage to get the device upgraded to Stock android >10 (which is marked a a mandatory requirement in both LineageOS and /e/OS doc). No OTA available (because the owner of the device had already unlocked the bootloader I guess), and no way to flash a manually downloaded upgrade..

I'm pretty sure I've read that instructions will be added to explain how to upgrade stock ROM. So I'm just pointing out that those instructions are important for this device.

It is the second device in 2 weeks that I test and is not flashing with OAI (FP3 and 7A). I think it is better to have a shorter list that is working 100% rather than a longer list with frustrating experience, which results in users not advertising the tool anymore.

**Comment by anon1892** [comment]
> I've spent more than 6 hours trying to flash the 7A, first time because I did not find the TWRP. Because it was not listed as 7A, but as SDM439

Nothing new here, Redmi 7A has been unified with others devices for years... By the way when OAI recognize this phone, it says "Mi439", it should put you on the right track (or a quick search for "TheRomYouWant Redmi 7A download"...). Potential mitigation: add TWRP link on the device config. (maybe it's already ok, don't remember)

> No OTA available (because the owner of the device had already unlocked the bootloader I guess)

Nothing to do with OAI, that's Xiaomi. I already answered to that, please see previous message.

> I'm pretty sure I've read that instructions will be added to explain how to upgrade stock ROM. So I'm just pointing out that those instructions are important for this device.

@tsterbak What do you think about adding some instructions for it? I think using `brand` metadata is enough... Or just a link to the website?

> It is the second device in 2 weeks that I test and is not flashing with OAI (FP3 and 7A). I think it is better to have a shorter list that is working 100% rather than a longer list with frustrating experience, which results in users not advertising the tool anymore.

Sorry about hat issue, I'm not the maintainer of FP3. But that's another issue. By the way, the tool works for `Mi439`, you don't even tested it.
