### ISSUE TITLE
Show error details when selecting wrong image or recovery

### ISSUE THREAD

**Issue by julianfoad** [openandroidinstaller-dev/openandroidinstaller#354]
When selecting an image or recovery that does not match the device codes, I was bothered by the lack of transparency and specificity in the error message, which just said the files "don't work with the device".

We now show an error message that gives the user a better clue about why we rejected the file they chose. It explicitly shows the discovered and expected device codes.

For instance:

> "This image lists support for device codes {supported_devices}. One of these should match one of your device's code names {supported_device_codes}."

For screen-shots see the [issue](https://lab.trax.im/fork/github/openandroidinstaller-dev/openandroidinstaller/-/issues/1) in my own repository.

For the patch, you can review [the diff](https://lab.trax.im/fork/github/openandroidinstaller-dev/openandroidinstaller/-/compare/dev...1-show-error-details-when-selecting-wrong-image-or-recovery) of [my branch](https://lab.trax.im/fork/github/openandroidinstaller-dev/openandroidinstaller/-/tree/1-show-error-details-when-selecting-wrong-image-or-recovery) against upstream `dev` branch (when I last synchronised it).

You can merge this into the `dev` branch of your fork using a standard `git` command *([why not a github PR?](https://wrily.foad.me.uk/foss-apps-live-in-foss-forges))*:

```
git pull https://lab.trax.im/fork/github/openandroidinstaller-dev/openandroidinstaller.git 1-show-error-details-when-selecting-wrong-image-or-recovery
```

**Comment by tsterbak** [comment]
Thank you! I will have a look and move forward merging it :)
