### ISSUE TITLE
Add support for `jasmine_sprout`

### ISSUE THREAD

**Issue by Blackcougar-ita** [openandroidinstaller-dev/openandroidinstaller#367]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

xiaomi

### Name

Mi A2

### Device code

`jasmine_sprout`

### Device images

```Markdown
Castom ROM: https://get.pixelexperience.org/jasmine_sprout
recovery: https://get.pixelexperience.org/jasmine_sprout
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Should be easy, but I don't have the time for now
https://wiki.pixelexperience.org/devices/jasmine_sprout/install/

**Comment by anon1892** [comment]
Hello @Blackcougar-ita , sorry for the wait.
Please look at #410 for testing, we can help you if needed :)
