### ISSUE TITLE
Add support for `K7_A101`

### ISSUE THREAD

**Issue by 2FFgithubc** [openandroidinstaller-dev/openandroidinstaller#369]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

VOLENTEX 

### Name

VOLENTEX Tablet 7 Inch Android Go 11

### Device code

K7_A101

### Model

K7

### Device images

```Markdown
- Custom ROM: https://wiki.lineageos.org/devices/
- Custom ROM: https://kaleidoscope.ink/download.html
- Custom ROM: https://calyxos.org/install/
- Custom ROM: https://ancientrom.xyz/download
- Custom ROM: https://downloads.blissroms.org/
- Custom ROM: https://kaleidoscope.ink/download.html
- Custom ROM: https://viperos.gitlab.io/download/
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
mmm not sure if this helps but here:

[2GB RAM + 32GB ROM] VOLENTEX Android tablets comes with 32GB of storage, which is larger than other 7 inch tablets, expandable up to a 128GB SD card (card not included)
[Powerful High Performance ] The tablet uses the latest Android 11.0 system. Powerful and energy-efficient Quad-core processor,which has a more energy-efficient operation method and faster processing speed than previous generations of systems and chips. This GMS certified Android 11 tablet comes with Android 11 operating system.

also its a small size, doesnt really run hot to my knowledge
```

**Comment by anon1892** [comment]
This device doesn't seem to have any development for custom ROM... I don't even find it on XDA
You should be able to install a GSI (Global System Image, works on all devices shipped with Android 8 or higher iirc), if the bootloader is unlockable, but OpenAndroidInstaller don't support GSI install, sorry...

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
