### ISSUE TITLE
Add support for `NOTE_20_PRO`

### ISSUE THREAD

**Issue by pcmagicien** [openandroidinstaller-dev/openandroidinstaller#370]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Cubot

### Name

Note 20 pro

### Device code

Device with code 'NOTE_20_PRO' is not supported yet.

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
This device doesn't seem to have any development for custom ROM... I don't even find it on XDA
You should be able to install a GSI (Global System Image, works on all devices shipped with Android 8 or higher iirc), if the bootloader is unlockable, but OpenAndroidInstaller don't support GSI install, sorry...

**Comment by SirRGB** [comment]
Sometimes stock roms have quirks, that might result in treble incompliance. One reason why Im personally against gsi compatibility in oai.
I also doubt that A8 vendors can even handle A12+.
A10 could be fine (the version this shipped with), but idk abt mtk support.
Btw there should be tools for mtk unlock. Currently only xiaomi mtk is supported, which uses its own process.

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
