### ISSUE TITLE
Add support for `B130DL`

### ISSUE THREAD

**Issue by pinkelefant808** [openandroidinstaller-dev/openandroidinstaller#371]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

TCL

### Name

Blue

### Model

B131DL

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by SirRGB** [comment]
Same as the previous request. This seems to be a niche device with no custom rom development. There doesnt seem to be a point in supporting this.
Even flashing addons is only possible with recovery and that is not given here.

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
