### ISSUE TITLE
Add support for `TB310XU`

### ISSUE THREAD

**Issue by Lenovo21** [openandroidinstaller-dev/openandroidinstaller#372]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Lenovo

### Name

TAB9

### Device code

NA

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
