### ISSUE TITLE
Add support for `PQ82A11`

### ISSUE THREAD

**Issue by Gitski** [openandroidinstaller-dev/openandroidinstaller#373]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

ZTE / Numbia

### Name

Z50 Ultra

### Device code

PQ82A11

### Model

NX712J

### Device images

```Markdown
https://oss.ztedevices.com/prod/cn/bigfile/2022/447300B12MR208MyOS13.0.12MR2_NX712J(SD%E5%8D%A1%E5%8D%87%E7%BA%A7%E5%8C%85).zip
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
This is a very good device but is hampered by the fact it is a Chinese Rom and is locked down to the point that it's an annoyance to use and not even the most basic of features can be modified in a meaningful way.

It would be great to get this device rooted or have a reasonably solid OS which allows for modifications of certain features like changing launchers etc.. 

Thank you
```

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
