### ISSUE TITLE
resizing/scaling support

### ISSUE THREAD

**Issue by SirRGB** [openandroidinstaller-dev/openandroidinstaller#379]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/79085035/e17ad289-ee6d-4a6a-be4b-2b0999687d11)
UI doesnt scale properly when resized
Tuxedo OS (kubuntu) flatpak 0.51

**Describe the solution you'd like**
resizing of pictures (especially useful if vectors are implemented, https://github.com/openandroidinstaller-dev/openandroidinstaller/pull/211) and textboxes.

**Comment by SirRGB** [comment]
![image](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/79085035/04f9c083-c88c-43f7-a45d-3b3442e19451)

This warning is cut off.
This is a .deb package, but behavior should be similar.

https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/fe5644f98ca05306d3e71cd63dbaebf3fa71f6ee/openandroidinstaller/views/requirements_view.py#L142

**Comment by tsterbak** [comment]
Hey, thanks for reporting this!
I will look into it!

**Comment by tsterbak** [comment]
Hopefully addressed by release v0.5.2-beta
