### ISSUE TITLE
Installer crashes when sideloading progress goes over 100%

### ISSUE THREAD

**Issue by SirRGB** [openandroidinstaller-dev/openandroidinstaller#380]
**Describe the bug**
When flashing Magisk the installer gets stuck.
Device seems to reboot into recovery.

**To Reproduce**
Install Magisk-v26.4.zip (renamed from apk) as addon.

**Expected behavior**
Flashing succeeds and you can continue.
Im fine with a disclaimer too since Magisk is not meant for the target audience of oai.

**Log file**
https://haste.aicp-rom.com/ujemuyewoq.sql

**Screenshots**
![image](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/79085035/96bdb8bd-37d7-4d8a-86b3-4038a76317c3)

**Desktop (please complete the following information):**
 - OS: Tuxedo OS 2, i.e. Kubuntu 22.04 LTS

**Smartphone (please complete the following information):**
 - Device: OnePlus 5
 - OS: crDroid 9.11
 - OAI Version 0.51

**Additional context**
![image](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/79085035/26d39a23-3906-4740-8d9c-7eed1697c5e0)
Manually sideloading causes >100% progress, which crashes the progress bar in oai.

**Comment by anon1892** [comment]
It may be related to #256, because it was working when I tested my PR (#222 for example)
However, adb's status progress was above 100%, so was OAI status bar too, but Magisk was installed correctly.

**Comment by tsterbak** [comment]
> It may be related to https://github.com/openandroidinstaller-dev/openandroidinstaller/pull/256, because it was working when I tested my PR (https://github.com/openandroidinstaller-dev/openandroidinstaller/pull/222 for example)

Yeah, I guess the issue with the progressbar was introduced here... I will fix it with the next release.

>  Install Magisk-v26.4.zip (renamed from apk) as addon.

Maybe we should also allow for apk sideloading? Do you see any downsides there?

**Comment by SirRGB** [comment]
I was able to flash the Magisk apk successfully using the dev branch, so consider this fixed.
Im not quite sure if we should allow apk sideloading in general since the Magisk apk is basically the only apk, that behaves like a zip as far as I know. Maybe allow *.zip and Magisk*.apk? Sideloading an unsupported apk just throws an error in the recovery...
