### ISSUE TITLE
Add support for `Pixi3-7`

### ISSUE THREAD

**Issue by Androtherion** [openandroidinstaller-dev/openandroidinstaller#385]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Alcatel

### Name

Pixi 3

### Device code

Device with code 'Pixi3-7' is not supported yet

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
I tried to backup the android table using adb but the backup file was 41 bytes long, a mistake I couldn't resolve. Also tried other tools on windows to no avail. I'm trying to install the ROM even without backup because the device is very much unusable as it is.
```

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
