### ISSUE TITLE
Add support for `shiva`

### ISSUE THREAD

**Issue by tonyngl777** [openandroidinstaller-dev/openandroidinstaller#391]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Xiaomi

### Name

POCO M2

### Device code

shiva

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Hello !  Can you test #392 please?

**Comment by tsterbak** [comment]
Merged and officially still untested.
