### ISSUE TITLE
Add support for `pissarroinpro`

### ISSUE THREAD

**Issue by reejit** [openandroidinstaller-dev/openandroidinstaller#393]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Xiaomi

### Name

11i Hypercharge

### Device code

pissarroinpro

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
I didn't find any custom ROM available for your device ([see xda](https://xdaforums.com/tags/pissarro/))
Without custom ROM, you will have to install GSI, that are unfortunately not supported by OpenAndroidInstaller...

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
