### ISSUE TITLE
Improve error message when ZIP ROm package does not have META-INF/com/android/metadata

### ISSUE THREAD

**Issue by freechelmi** [openandroidinstaller-dev/openandroidinstaller#394]
**Is your feature request related to a problem? Please describe.**
I tried  to flash a TWRP flashable ZIP containing a stock rom ( https://bit.ly/4ar1VWU) 
 that does not have a   META-INF/com/android/metadata

**Describe the solution you'd like**
either change the criteria for image_works_with_device() function 
or display a complete error message explaining why the ZIp file is not accepted

**Describe alternatives you've considered**
A clear message in RED saying " This zip file is rejected because XXXXX "

**Additional context**

**Comment by tsterbak** [comment]
Thats a really good point! I will look into it :)

**Comment by tsterbak** [comment]
Should be resolved with the next release :)
