### ISSUE TITLE
Add support for `a03su`

### ISSUE THREAD

**Issue by revdlcat** [openandroidinstaller-dev/openandroidinstaller#396]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Samsung

### Name

Galaxy AO3s

### Device code

ao3su

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
