### ISSUE TITLE
Add support for `Armor_6E`

### ISSUE THREAD

**Issue by FlightMedicALX** [openandroidinstaller-dev/openandroidinstaller#397]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

ulefone

### Name

Armor_6E

### Device code

Armor_6E

### Model

Armor 6E

### Device images

```Markdown
https://firmwarefile.com/ulefone-armor-6e
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
