### ISSUE TITLE
Add support for `cv3`

### ISSUE THREAD

**Issue by dafman1102** [openandroidinstaller-dev/openandroidinstaller#401]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

lg

### Name

lm-x410.fgn

### Device code

no code

### Model

k30

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
tried to connect through app and the popup message i got brought me too here.
```

**Comment by tsterbak** [comment]
No custom ROM available or in the making as far as I can tell. If you don't agree, please respond to this and we might reopen the issue :)
