### ISSUE TITLE
Add support for `HWVOG`

### ISSUE THREAD

**Issue by k4my4b** [openandroidinstaller-dev/openandroidinstaller#411]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Huawei

### Name

P30 pro

### Device code

HWVOG

### Model

VOG-L09

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by SirRGB** [comment]
This device doesnt have any development nor is it unlockable and thus it is impossible for custom roms to even run on this phone. OAI aims to simplify the installation of _**existing**_ roms, but since there are none for your device there wont be any support for the p30 pro.
