### ISSUE TITLE
Add support for `Sunmi V2` on OpenAndroidInstaller

### ISSUE THREAD

**Issue by marnet54** [openandroidinstaller-dev/openandroidinstaller#414]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Sunmi

### Name

V2

### Device code

Device with code 'V2' is not supported yet.

### Model

V2

### Device images

```Markdown
Unable to found original Firmware

https://www.sunmi.com/en-US/v2/
https://m.media-amazon.com/images/I/51SZjmLXEoL._SY445_SX342_QL70_ML2_.jpg
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
I want to use device like a smartphone: phone calls and sms.
The integrated printer: I can take photo and put on sheet immediatly.
Thank's
```

**Comment by anon1892** [comment]
Hello,
There is no development for this device, so we will not be able to support it...
You may root it ([link](https://xdaforums.com/t/firmware-root-method-sunmi-v2.4531909/)), but I didn't find anything else.
