### ISSUE TITLE
Add support for `I14_Pro_Max`

### ISSUE THREAD

**Issue by bilalbagelbaig** [openandroidinstaller-dev/openandroidinstaller#415]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

I14_Pro_Max

### Name

I14_Pro_Max

### Device code

Oreo MR1

### Model

I14_Pro_Max

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Hello,
There is no development for this device, so we will not be able to support it...
