### ISSUE TITLE
Unable to select LMODroid

### ISSUE THREAD

**Issue by SirRGB** [openandroidinstaller-dev/openandroidinstaller#416]
**Describe the bug**
When trying to select the `LMODroid-4.2-20240107-RELEASE-cheeseburger.zip` package it simply doesnt work. Selecting the Lineage Package and then the LMO one does let you continue the process and still flashes the LMO package for some reason.

**To Reproduce**
1. Connect device
2. Fill requirement checkboxes
3. Select `lineage-20.0-20240108-nightly-cheeseburger-signed.zip`
4. Select `LMODroid-4.2-20240107-RELEASE-cheeseburger.zip`
5. Continue normal process.

**Expected behavior**
Selecting LMO should not throw an error.

**Log file**
https://haste.aicp-rom.com/hixofimibe.sql

**Desktop (please complete the following information):**
 - OS: Tuxedo OS 2, based on Ubuntu 20.04 LTS
 - Version 0.52 dev, 379-resizingscaling-support

 - **Smartphone (please complete the following information):**
 - Device: OnePlus 5
 - OS: crDroid -> LMODroid
 - Version 9.12 -> 4.2

**Comment by SirRGB** [comment]
![grafik](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/79085035/4538fe8d-37d6-48e6-97ac-e3afb877468f)

You can tick the checkboxes and untick them and it still satisfies the checks, so after all conditions are met all checks are disabled. Still doesnt explain the lmo bug (regex stuff ig), but could be helpful.

**Comment by anon1892** [comment]
Can you provide a link to the file, please?

**Comment by SirRGB** [comment]
> Can you provide a link to the file, please?

Sure thing, here it is

https://get.libremobileos.com/builds/full/cheeseburger/20240107/LMODroid-4.2-20240107-RELEASE-cheeseburger.zip
https://get.libremobileos.com/devices/cheeseburger/builds

**Comment by anon1892** [comment]
The fun fact is that I have no problem with `LMODroid-4.2-20240107-RELEASE-cheeseburger.zip`...
But I have found another problem with `IMG-e-1.18-t-20231207360613-stable-FP5.zip` (which can't be flashed by OAI because it's a very strange installation package)

**Comment by anon1892** [comment]
Is this bug still present on the latest version? @SirRGB

**Comment by SirRGB** [comment]
No, I also couldnt replicate it in the version, that I thought I had the issue on. Ig I shouldve double-checked. The logs suggest, that I might not have chosen a zip.

> ![grafik](https://private-user-images.githubusercontent.com/79085035/295923172-4538fe8d-37d6-48e6-97ac-e3afb877468f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMTgzODUsIm5iZiI6MTcwNjExODA4NSwicGF0aCI6Ii83OTA4NTAzNS8yOTU5MjMxNzItNDUzOGZlOGQtMzdkNi00OGU2LTk3YWMtZTNhZmI4Nzc0NjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDE3NDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMDRmNDM5NTkxMzk3MTIzOThkNGE2NmI5OGNkNDdkOWUzM2E1MmRjMGRmNmY4MGQ3ZGY3NWE5NGRlNzJmMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UftUWaj1dyXUK9dMfEbyfonueYkJJba4RZylWm_KBOs)
> 
> You can tick the checkboxes and untick them and it still satisfies the checks, so after all conditions are met all checks are disabled. Still doesnt explain the lmo bug (regex stuff ig), but could be helpful.

This is still present though, but only visual, so I dont think it is important...
