### ISSUE TITLE
Support for sideloading vb_meta.img and stuff.

### ISSUE THREAD

**Issue by tsterbak** [openandroidinstaller-dev/openandroidinstaller#42]
Should help to enable devices like #32.

**Comment by tsterbak** [comment]
For example this device needs it: https://wiki.lineageos.org/devices/lemonadep/

**Comment by tsterbak** [comment]
@MagicLike @SirRGB @freechelmi 
Where could additional file selection buttons and displays fit in? :thinking:

**Comment by MagicLike** [comment]
> @MagicLike @SirRGB @freechelmi Where could additional file selection buttons and displays fit in? thinking

Maybe at the OS and TWRP file selection?

**Comment by MagicLike** [comment]
This could also get fixed by #188 (?)

**Comment by tsterbak** [comment]
Yes, I think so.

**Comment by tsterbak** [comment]
Resolved with #246
