### ISSUE TITLE
Add support for `P63L`

### ISSUE THREAD

**Issue by Jweim1983** [openandroidinstaller-dev/openandroidinstaller#428]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

PCD

### Name

P63L

### Device code

Device with code 'P63L' is not supported yet.

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Hello, thanks for your interest in this project !
I didn't find any custom ROM for this device... We will not be able to support your device.

**Comment by Jweim1983** [comment]
ok thank you , i ended up just pulling it MTK client

**Comment by anon1892** [comment]
Without installing custom ROM, am I right? (or maybe GSI)
