### ISSUE TITLE
Component not found; installation not possible on Fedora Atomic

### ISSUE THREAD

**Issue by gluckgluckwasserbauch** [openandroidinstaller-dev/openandroidinstaller#429]
On issue #422, I thought I couldn't install because the device isn't supported yet.  
As we found out, it isn't because of the missing support, but due to some misbehaviour on my distro.  

# Error and backgrounds  
## Error  
The error is: `'/system/bin/sh: grep: not foun'`  

## System information  
**OS**: Fedora Atomic (the immutable variants of Fedora), to be more precise, the `kinoite-main`-image from universal-blue.org. 
But I think it should be reproducible for every other image-based Fedora flavour too, maybe even for other distros like NixOS, OpenSuse MicroOS or VanillaOS.
**Installation method:** Flatpak from flathub.org; I didn't try it with Distrobox yet. Would lead to the same problem I guess.

## Potential reason  
As far as I (no expert) can guess, this is due to some missing symlinks.
Image-distros use a lot of symlinks to get around the permission problems. Just to visualize, here's a screenshot of my file system: 
![Screenshot_20240123_114545](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/99470494/7521318c-712b-4b88-bed4-164068ffe6ce)
Every chain symbol on the icon shows that this folder is just a symlink. And there are a lot of them, including the /bin/ folder, where `sh` should be located for the installer to make use of.

# Solution  
Add a line of something like "if /bin/sh not found, then use /usr/bin/sh instead".

I would like to offer you that I can try it out myself, but sadly, I have zero coding experience. Even the bug report was a bit challenging for me... :sweat:

**Comment by anon1892** [comment]
Thank you, we will look at it! (I'm busy these days...)
>  As we found out, it isn't because of the missing support, but due to some misbehaviour on my distro.

There is a bug with your distro, but your phone is not yet supported too (so we keep open #422)

**Comment by tsterbak** [comment]
Should be resolved with the next release :) Let me know if this error still persists and we can open it again.
