### ISSUE TITLE
Add support for `OP4F4DL1`

### ISSUE THREAD

**Issue by giabra56** [openandroidinstaller-dev/openandroidinstaller#430]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

oppo

### Name

A94 5g

### Device code

Device with code 'OP4F4DL1' is not supported yet.

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Hello, thanks for your interest in this project !
I didn't find any custom ROM for this device... We will not be able to support your device.
And as far I know, Oppo bootloader can't be unlocked...
