### ISSUE TITLE
Add support for `OP4EF3L1`

### ISSUE THREAD

**Issue by ahamedrashid-me** [openandroidinstaller-dev/openandroidinstaller#455]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Oppo

### Name

Oppo F17

### Device code

OP4EF3L1

### Model

Oppo F17

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Hello, thanks for your interest in this project.
I didn't find any custom ROM for this device... If there isn't, we will not be able to support your device.
