### ISSUE TITLE
Add support for `A51`

### ISSUE THREAD

**Issue by HackerNick04** [openandroidinstaller-dev/openandroidinstaller#457]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Samsung

### Name

Galaxy A51

### Device code

a515xelte

### Model

SM-A515F/DSN

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
Thank you for your interest in the project.

There is currently no custom ROM or TWRP recovery available for this device or in the making as far as I can tell.

If you don't agree, please respond to this and we might reopen the issue :)
