### ISSUE TITLE
Add support for `cyprus64`

### ISSUE THREAD

**Issue by w-wShadow-w** [openandroidinstaller-dev/openandroidinstaller#460]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Motorola

### Name

moto e40

### Device code

none

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Hello, thanks for your interest in this project.
I didn't find any custom ROM for this device... If there isn't, we will not be able to support your device.
