### ISSUE TITLE
Add support for `espresso10wifi`

### ISSUE THREAD

**Issue by John194950** [openandroidinstaller-dev/openandroidinstaller#461]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Samsung

### Name

Galaxy Tab 2 10.1

### Device code

espresso10wifi

### Model

GT-P5110

### Device images

```Markdown
https://www.gsmarena.com/samsung_galaxy_tab_2_10_1_p5110-4669.php

Would like to upgrade to latest viable version of Android.
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
Open Android Installer version 0.5.2-beta used with this device (21/02/2024). It indicates that device with code 'espresso10wifi'is not supported yet and that I should request support for this device.
```

**Comment by tsterbak** [comment]
Thank you for your interest in the project.

There is currently no custom ROM or TWRP recovery available for this device or in the making as far as I can tell.

If you don't agree, please respond to this and we might reopen the issue :)
