### ISSUE TITLE
Add support for  chinese  mediatek  8752    `T900`

### ISSUE THREAD

**Issue by hansie1315** [openandroidinstaller-dev/openandroidinstaller#463]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

mediatek

### Name

chinese

### Device code

t900

### Model

t900

### Device images

```Markdown
10 inch octacore
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
its  a chinese tablet with a mediatek 8752 in it
```

**Comment by anon1892** [comment]
Hello, thanks for your interest in this project.
I didn't find any custom ROM for this device... If there isn't, we will not be able to support your device.

**Comment by hansie1315** [comment]
okay thanks,
________________________________
Van: Rudu ***@***.***>
Verzonden: dinsdag 5 maart 2024 20:51
Aan: openandroidinstaller-dev/openandroidinstaller ***@***.***>
CC: hansie1315 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [openandroidinstaller-dev/openandroidinstaller] Add support for chinese mediatek 8752 `T900` (Issue #463)


Hello, thanks for your interest in this project.
I didn't find any custom ROM for this device... If there isn't, we will not be able to support your device.
