### ISSUE TITLE
Add support for `borago`

### ISSUE THREAD

**Issue by wojpot** [openandroidinstaller-dev/openandroidinstaller#467]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

motorola

### Name

e22i

### Device code

borago

### Model

e22i

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
13
```

**Comment by anon1892** [comment]
Hello, thanks for your interest in this project.
I didn't find any custom ROM for this device... If there isn't, we will not be able to support your device.
