### ISSUE TITLE
Add support for `Elite_OctaPlusKK1`

### ISSUE THREAD

**Issue by frankhenriquez19** [openandroidinstaller-dev/openandroidinstaller#468]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Sky Devices

### Name

Elite OctaPlus

### Device code

Elite_OctaPlusKK1

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Hello, thanks for your interest in this project!
I didn't find any custom ROM for this device... We will not be able to support your device.
