### ISSUE TITLE
Add support for `Bora_TF`

### ISSUE THREAD

**Issue by WilliamAfton1938** [openandroidinstaller-dev/openandroidinstaller#472]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

tcl

### Name

ion v

### Device code

bora_tf

### Model

t607DL

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Hello, thanks for your interest in this project!
I didn't find any custom ROM for this device... If there isn't, we will not be able to support your device.
