### ISSUE TITLE
Add support for `a03su`

### ISSUE THREAD

**Issue by Hisnamewasgod** [openandroidinstaller-dev/openandroidinstaller#475]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

samsung

### Name

samsung galaxy a03

### Device code

a03su

### Model

SM-S134DL

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
There is currently no custom ROM or TWRP recovery available for this device or in the making as far as I can tell.

If you don't agree, please respond to this and we might reopen the issue :)
