### ISSUE TITLE
Add support for `M0222_ND`

### ISSUE THREAD

**Issue by mccdxxx** [openandroidinstaller-dev/openandroidinstaller#477]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

blu

### Name

m8l 2022

### Device code

mo222_nd

### Model

m8l 2022

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
There is currently no custom ROM or TWRP recovery available for this device or in the making as far as I can tell.

If you don't agree, please respond to this and we might reopen the issue :)
