### ISSUE TITLE
Add support for `ASUS_X00R_5

### ISSUE THREAD

**Issue by kanu76** [openandroidinstaller-dev/openandroidinstaller#478]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

asus

### Name

asus l1

### Device code

no

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
There is currently no custom ROM or TWRP recovery available for this device or in the making as far as I can tell.

If you don't agree, please respond to this and we might reopen the issue :)
