### ISSUE TITLE
Add support for Motorola moto g6

### ISSUE THREAD

**Issue by Motoroli** [openandroidinstaller-dev/openandroidinstaller#480]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Motorola

### Name

Moto g6

### Device code

ali_n

### Model

XT1925-5

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
There is currently no custom ROM or TWRP recovery available for this device or in the making as far as I can tell.

If you don't agree, please respond to this and we might reopen the issue :)

**Comment by tsterbak** [comment]
There is currently no custom ROM or TWRP recovery available for this device or in the making as far as I can tell.

If you don't agree, please respond to this and we might reopen the issue :)
