### ISSUE TITLE
Add support for `Boston`

### ISSUE THREAD

**Issue by Dfuas1** [openandroidinstaller-dev/openandroidinstaller#485]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

TCL

### Name

TCL 10 PLUS

### Device code

Boston

### Model

T782H

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
There is currently no custom ROM or TWRP recovery available for this device or in the making as far as I can tell.

If you don't agree, please respond to this and we might reopen the issue :)
