### ISSUE TITLE
Add support for `sofia`

### ISSUE THREAD

**Issue by stretchcraft** [openandroidinstaller-dev/openandroidinstaller#491]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Motorola

### Name

moto g power

### Device code

sofia

### Model

XT2041DL

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
Unfortunately there seems to be no version of TWRP available for this device, which is required for the installer to work.
If you think I'm wrong, please reopen this issue! :)

**Comment by tsterbak** [comment]
Unfortunately there seems to be no version of TWRP available for this device, which is required for the installer to work.
If you think I'm wrong, please reopen this issue! :)

**Comment by tsterbak** [comment]
Unfortunately there seems to be no version of TWRP available for this device, which is required for the installer to work.
If you think I'm wrong, please reopen this issue! :)
