### ISSUE TITLE
Add support for `V2236`

### ISSUE THREAD

**Issue by SgtQuiet** [openandroidinstaller-dev/openandroidinstaller#499]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

vivo

### Name

vivo 02

### Device code

vivo

### Model

523860

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
i want to instal a new android
```

**Comment by anon1892** [comment]
Hello, thanks for your interest in this project!
I didn't find any custom ROM for this device... If there isn't, we will not be able to support your device.
