### ISSUE TITLE
Windows : DLL missing out of the box

### ISSUE THREAD

**Issue by anon1892** [openandroidinstaller-dev/openandroidinstaller#502]
I've just tested running OAI from a Windows virtual machine, and I'm facing the following error : `MFPlat.dll` is missing.
I'm running Windows 10 Pro Education N 22H2. Log file is empty.

![image](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/40572253/5eb04ea2-7d4a-450f-bbf2-5ff171669be3)

I downloaded the missing dll, and copied and pasted it into C:/Windows/System32
Now, I need `MSVCP110.dll`. Note that an infinitely downloading windows appears (OAI, but wrong logo)

![image](https://github.com/openandroidinstaller-dev/openandroidinstaller/assets/40572253/14c7ae60-473e-4a57-b8b4-fbf9058c1939)

And I'm stuck at this point (but it was just for testing)

EDIT : I've also tested on another Windows machine (working for years, with a lot of stuff on it) and it works well. 
It would be better if all dependencies are bundled in the .exe, just in case, isn't it?

**Comment by tsterbak** [comment]
Unfortunately it is not possible to bundle all dependencies in the .exe. On one hand every machine might need different dependencies and on the other hand licence issues (especially with windows). On linux systems the flatpak provides a package with basically all dependencies backed in.

On windows it can help to install some c++ libraries: https://openandroidinstaller.org/faq.html#dll-missing

**Comment by anon1892** [comment]
Linux in our hearts :heart: 
If it's not possible, I close this issue, it was just for information...
