### ISSUE TITLE
Add support for `HWJLN-Q`

### ISSUE THREAD

**Issue by PRIYANGA415** [openandroidinstaller-dev/openandroidinstaller#506]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Huawei

### Name

Nova 9 SE

### Device code

HWJLN-Q

### Model

JLN-LX1

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Hello, thanks for your interest in this project.
Unfortunately, Huawei don't allow anymore to unlock the bootloader since 2018, so custom ROMs can't be installed on their phone...
