### ISSUE TITLE
Add support for `SmartPadS2`

### ISSUE THREAD

**Issue by mauroottavi** [openandroidinstaller-dev/openandroidinstaller#510]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

mediacom

### Name

M-Mp1040S2

### Device code

SmartPadS2

### Model

M-Mp1040S2

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Hello, thanks for your interest in this project!
I didn't find any custom ROM for this device... If there isn't, we will not be able to support your device.
