### ISSUE TITLE
Add support for `OP5958L1`

### ISSUE THREAD

**Issue by meansmd1** [openandroidinstaller-dev/openandroidinstaller#512]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

OnePlus

### Name

Nord N30

### Device code

Nord N30

### Model

OP5958L1

### Device images

```Markdown
OP5958L1
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
Already requested: #489
