### ISSUE TITLE
Add support for `violet`

### ISSUE THREAD

**Issue by harshangithub** [openandroidinstaller-dev/openandroidinstaller#516]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Xiaomi Redmi

### Name

Note 7 Pro

### Device code

violet

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
I've just created the config file for `violet` : #517 
Can you test it please?

**Comment by harshangithub** [comment]
is is it updated to the app
________________________________

**Comment by harshangithub** [comment]
cuz i dont know much about developing and I am a starter in developing
________________________________

**Comment by anon1892** [comment]
It's not yet updated, but it's easy : download latest OpenAndroidInstaller executable [here](https://github.com/openandroidinstaller-dev/openandroidinstaller/releases/tag/v0.5.3-beta) (.exe on Windows for instance),
then place the configuration file I've created (download it [here](https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/d27116741810ddd327ef8c5f9b80eb794b28ec7c/openandroidinstaller/assets/configs/violet.yaml), with top right download icon) in the same directory as the executable. OpenAndroidInstaller should recognize the new config file.

**Comment by harshangithub** [comment]
It works fine. But there are some issues where the ROM won't boot normally it always goes to the bootloader. I also noticed one spelling mistake in the program 
--->In the first screen it is thought. spelling mistake: though

**Comment by anon1892** [comment]
> The ROM won't boot normally it always goes to the bootloader.

Thank you for testing! So... It doesn't work for now... Which ROM & recovery did you tried?
I think it needs additional partitions to be flashed, like `dtbo` or so... Can you provide the installation documentation for the ROM you tried? And perhaps the logs or OpenAndroidInstaller, maybe an error was not handled as it should be? Thanks!

And thank you for reporting the spelling mistake!

**Comment by anon1892** [comment]
Uh, I think I've found the problem: additional partitions were asked but not flashed...
It's corrected with the last commit. Can you please download the latest config file [here](https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/5ac5d44d3206ff1231fd9cbf3422d7672d48cb16/openandroidinstaller/assets/configs/violet.yaml) and try again? :pray:

**Comment by harshangithub** [comment]
oh i ve just fixed it i re flashed the rom and worked fine Thank You!
________________________________

**Comment by harshangithub** [comment]
I used the latest config file you gave
________________________________

**Comment by anon1892** [comment]
Nice, thank you for your help!

**Comment by anon1892** [comment]
Just to be sure, do you changed something else (like the ROM you flashed or so)?

**Comment by harshangithub** [comment]
nah its the same
________________________________

**Comment by harshangithub** [comment]
i installed lineage os btw
________________________________

**Comment by anon1892** [comment]
Ok, thanks!

**Comment by tsterbak** [comment]
Merged now and will be part of the next release! Thanks a lot for your work folks! :)
