### ISSUE TITLE
Add support for `EF500`

### ISSUE THREAD

**Issue by Christodevil** [openandroidinstaller-dev/openandroidinstaller#521]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

bluebird

### Name

bluebird 

### Device code

EF500 is not supported yet

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Hello, thanks for your interest in this project!
I didn't find any custom ROM for this device... If there isn't, we will not be able to support your device.

**Comment by Christodevil** [comment]
How do I get the information required ?Sent from my iPhoneOn 4 May 2024, at 13:58, Rudu ***@***.***> wrote:﻿
Hello, thanks for your interest in this project!
I didn't find any custom ROM for this device... If there isn't, we will not be able to support your device.

**Comment by anon1892** [comment]
Each Android build is device specific, meaning that you can't install a build for another device on your without breaking it completely. So for every device, developers have to work to provide a working ROM. After that, they give some speific `.zip` and `.img` files (like [here](https://download.lineageos.org/devices/rosemary/builds) for Redmi Note 10S for instance)
But for your device, I didn't find such files, so I don't know how to create the OpenAndroidInstaller configuration file for this device (installation process depends on the device...)
