### ISSUE TITLE
Add support for Lenovo `TB-8304F`

### ISSUE THREAD

**Issue by Rjose123** [openandroidinstaller-dev/openandroidinstaller#530]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Lenovo 

### Name

Tab 4 8

### Device code

HKL455NZ

### Model

TB-8304F

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
