### ISSUE TITLE
Add support for `Pad6`

### ISSUE THREAD

**Issue by josueco123** [openandroidinstaller-dev/openandroidinstaller#531]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

XSD

### Name

Pad6

### Device code

Pad6

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by anon1892** [comment]
Hello, thanks for your interest in this project!
I didn't find any custom ROM for this device... If there isn't, we will not be able to support your device.
