### ISSUE TITLE
Dark mode complaints

### ISSUE THREAD

**Issue by clstaudt** [openandroidinstaller-dev/openandroidinstaller#54]
When starting the app it runs in UI dark mode (my OS default). A few issues appear:

- white text on yellow background is hard to read
- the workflow diagram isn't properly displayed on the dark background

![Screenshot 2023-01-09 at 19 53 22](https://user-images.githubusercontent.com/875194/211385854-5f435dbb-7e90-4285-947a-f9631ba63053.png)
![Screenshot 2023-01-09 at 19 53 53](https://user-images.githubusercontent.com/875194/211385863-39b90ce6-0b56-49dd-a5cb-7ca3971b40db.png)

**Comment by tsterbak** [comment]
Ah yes, good point!

I guess my solution for now will be to just force "light mode". I don't want to put work in a second or new color mode.
Will be addressed in the next release. (#51)

**Comment by clstaudt** [comment]
![](https://i.redd.it/ltj1urgamqq21.jpg)
