### ISSUE TITLE
Add support for `2116`

### ISSUE THREAD

**Issue by Notshiahb** [openandroidinstaller-dev/openandroidinstaller#546]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Vivo

### Name

Y75

### Device code

865700056744757

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
There is currently no custom ROM or TWRP recovery available for this device or in the making as far as I can tell.

If you don't agree, please respond to this and we might reopen the issue :)
