### ISSUE TITLE
Add support for <G0890>

### ISSUE THREAD

**Issue by 5GIGABYTE** [openandroidinstaller-dev/openandroidinstaller#549]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Blu Phones

### Name

G33

### Device code

G0890

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
