### ISSUE TITLE
Add support for `X19Life`

### ISSUE THREAD

**Issue by AhmadShiraz** [openandroidinstaller-dev/openandroidinstaller#550]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

atouch

### Name

tablet PC

### Device code

Add support for `X19Life`

### Model

X19Life

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
