### ISSUE TITLE
Add support for `HS2`

### ISSUE THREAD

**Issue by rachitag112** [openandroidinstaller-dev/openandroidinstaller#551]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Micromax

### Name

Micromax HS2

### Device code

HS2

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
