### ISSUE TITLE
Add support for `VIVAQ7LIFE`

### ISSUE THREAD

**Issue by Al3sz** [openandroidinstaller-dev/openandroidinstaller#552]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Allview

### Name

VIVA Q7 Life

### Device code

VIVAQ7LIFE

### Device images

```Markdown
- Recovery: https://www.allview.ro/viva-q7-life.html#
Mention: it is under 'Descarcari' button
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
