### ISSUE TITLE
Add support for `RE58AF`      Realme C33  RMX3627

### ISSUE THREAD

**Issue by Amr-Nour-IT** [openandroidinstaller-dev/openandroidinstaller#558]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Realme

### Name

Realme C33

### Device code

RE58AF

### Model

RMX3627

### Device images

```Markdown
official Rom:   https://oppostockrom.com/realme-c33-2023-rmx3627
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
This device is not support OEM unlocking
```

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
