### ISSUE TITLE
LineageOS + OnePlus 6

### ISSUE THREAD

**Issue by kaffeeringe** [openandroidinstaller-dev/openandroidinstaller#56]
![Installer](https://user-images.githubusercontent.com/367592/212725416-b0d718cd-1963-4086-b9fe-c652df645b50.png)
I donwloaded the latest nightly of LineageOS 20.0 and 19.1 - both don't seem to be the right version. What am I doing wrong?

**Comment by tsterbak** [comment]
Hey, first of all, thank you for your interest in the project! And thank you for reporting this issue.

I guess I can see the reason for this bug. It's related to how OnePlus treats their devices device_code.
The device_code of that device is "OnePlus6" and the official code name of the device is "enchilada". For most vendors this seems to be the same thing. I'm checking in the tool if the device code matches the code name specified in the LineageOS zip. In this case they happened to not match...

I will address this in the next release later this week. If you want to progress in the mean time, you can update the "pre-device" field in the LineageOS zip, in the text file `META-INF/com/android/metadata` from "OnePlus6" to "enchilada". Then the compatibility checks should let you continue. (And hopefully this doesn't hurt LineageOS in some otherway...) The safest way would be to wait for the release and try again on the weekend :) 
Let me know if you have any questions! I'm super happy for all the feedback I can get! :)

**Comment by kaffeeringe** [comment]
Hej! Thank you for the quick answer and of course for this software. I struggled for a long time with the process without this software. It took me years to get my old tablet to LineageOS. And now it's only a few clicks!? Awesome!

Your workaround worked! (With LOS 19.1 - with 20.0 it didn't)

But: The next step starts the bootloader. That works I see the menu and I see, that my phone is still locked. But the next step doesn't work. The fastboot-window opens but nothing happens.

**Comment by tsterbak** [comment]
Hey :) Thanks for your kind words! I hope I'll get your issue resolved and make the process really easy for you :)

Thanks for persisting and trying the workaround. (Curious that it didn't work for LOS20)

Are you trying the tool on windows? Could you attach the log file here? (The file should be in the same directory as the executable) Then I can further investigate. :)

**Comment by kaffeeringe** [comment]
Oh no! Now:

>serving: 'H:\LineageOS\lineage-20.0-20230110-nightly-enchilada-signed.zip'  (~47%)    adb: failed to read command: No error
>$adb shell twrp wipe dalvik

**Comment by kaffeeringe** [comment]
Uh, But it boots anyway. And it seems to work. I was able to set it up.

**Comment by kaffeeringe** [comment]
Sadly no. The update didn't fix that. I guess, this is a LineageOS-problem.

**Comment by kaffeeringe** [comment]
But thank you! The tool works pretty well.

**Comment by kaffeeringe** [comment]
Factory-reset helped.

**Comment by tsterbak** [comment]
Hey, thank you for your effort and your feedback! :) It helps me a lot!

> serving: 'H:\LineageOS\lineage-20.0-20230110-nightly-enchilada-signed.zip' (~47%) adb: failed to read command: No error
$adb shell twrp wipe dalvik

This issue actually happens with most LineageOS versions and with regards to the LineageOS documentation, is expected but not a problem for the process. Seems to be an adb issue.

So you got LineageOS 20 successfully installed? Would you say a general hint towards using a factory reset would help users? I try to do that automatically in TWRP, but that usually fails/only partially succeeds for A/B-partitioned devices...

**Comment by kaffeeringe** [comment]
Yes. I guess a factory reset should always help. I read some posts. This error seems to be a common problem and the solutions seems to be to delete the app cache. A factory reset seems to do the same. 

It would be cool, if your installer optionally installed F-Droid. I guess, that is the first thing, most people do.

**Comment by tsterbak** [comment]
Very good point! I haven't thought about F-droid so far. I'm currently working on a solution to optionally flash Gapps or microg, but F-droid actually should be more straight-forward (because of less OS dependencies) and very useful immediately.
So hopefully that will be possible sometime next month :)

**Comment by kaffeeringe** [comment]
MicroG and GApps would be cool too for people who want to pass the phone on to someone less experienced.

**Comment by famo** [comment]
FYI
https://lineage.microg.org/
