### ISSUE TITLE
Add support for `mimir`

### ISSUE THREAD

**Issue by Vesper01** [openandroidinstaller-dev/openandroidinstaller#560]
### Is your device already requested?

- [ ] I have searched the existing issues

### Brand

ZTE

### Name

sonata 3

### Device code

mimir

### Model

Z832

### Device images

```Markdown
cant find it
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
its a zte sonata 3 the device code is mimir model number Z832 and im trying to install a different operating system on it
```

**Comment by tsterbak** [comment]
There is currently no custom ROM or TWRP recovery available for this device or in the making as far as I can tell.

If you don't agree, please respond to this and we might reopen the issue :)

**Comment by tsterbak** [comment]
There is currently no custom ROM or TWRP recovery available for this device or in the making as far as I can tell.

If you don't agree, please respond to this and we might reopen the issue :)
