### ISSUE TITLE
Add support for `TB-8506F`

### ISSUE THREAD

**Issue by AWDmaster** [openandroidinstaller-dev/openandroidinstaller#561]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Lenovo

### Name

M8 Rev.3

### Device code

Device with code 'TB-8506F' is not supported yet.

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
.
```

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
