### ISSUE TITLE
Add support for `W7413B`

### ISSUE THREAD

**Issue by Rafranurb** [openandroidinstaller-dev/openandroidinstaller#565]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

neso

### Name

w7413b

### Device code

w7413b

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by Rafranurb** [comment]
esta tablet quedo  obsoleta en la mayoria de las funciones, por el  android antigüo y fallas por actualizaciones

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
