### ISSUE TITLE
Add support for `DSH98123`

### ISSUE THREAD

**Issue by Lucifer6667788** [openandroidinstaller-dev/openandroidinstaller#573]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

wingtech

### Name

celero 5g

### Device code

Device with code 'DSH98123' is not supported yet.

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
