### ISSUE TITLE
Add support for `HWNAM`-lx9 / Huawei Nova 9

### ISSUE THREAD

**Issue by B3b0user** [openandroidinstaller-dev/openandroidinstaller#574]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Huawei

### Name

Nova 9

### Device code

HWNAM

### Model

NAM-LX9

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
