### ISSUE TITLE
miranari127@gmail.com

### ISSUE THREAD

**Issue by miranAri127** [openandroidinstaller-dev/openandroidinstaller#577]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

huawei

### Name

huawei y8s

### Device code

ftrfyitfgviuhb76

### Model

JKM-LX1

### Device images

```Markdown
https://fdn2.gsmarena.com/vv/pics/huawei/huawei-y8s-1.jpg
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
Y8S
```

**Comment by freechelmi** [comment]
Huawei devices cannot be unlocked anymore so I would close the device issue as Won't fix

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
