### ISSUE TITLE
Add support for `HWJKM-H`

### ISSUE THREAD

**Issue by miranAri127** [openandroidinstaller-dev/openandroidinstaller#578]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

huawei

### Name

huawei y8s

### Device code

865912041708827

### Model

JKM-LX1

### Device images

```Markdown
https://fdn2.gsmarena.com/vv/pics/huawei/huawei-y8s-1.jpg
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
Y8S
```

**Comment by miranAri127** [comment]
dssxdhf

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
