### ISSUE TITLE
Bootloader unlock options

### ISSUE THREAD

**Issue by tsterbak** [openandroidinstaller-dev/openandroidinstaller#58]
auf dem Eingangsbildschirm
- Schalter ob Bootloader bereits entsperrt ist ohne, dass das Gerät erkannt wurde setzbar machen

im Bootloader Unlock Step

- Falls man vergessen hat den Schalter vorher zu setzen, hier einfach nochmal einen Button einbauen um es zu überspringen

**Comment by SirRGB** [comment]
Das könnte evtl helfen das ganze bei non-samsung Geräten zu automatisieren. Mit regex könnte man das glaub ganz gut rausfiltern...

fastboot oem device-info

https://www.alphr.com/check-bootloader-is-unlocked/

**Comment by tsterbak** [comment]
Das hört sich möglicherweise nach einem guten Ansatz an.

Weißt du zufällt ob man das auch über adb direkt auslesen könnte? Das würde denn Prozess unter Umständen vereinfachen :)

**Comment by SirRGB** [comment]
Man kann diesen Wert auslesen. Zeigt aber glaub nur ob oem-unlocking in den dev-Einstellungem aktiviert wurde...

https://github.com/LineageOS/android_device_oneplus_msm8998-common/blob/lineage-20/system.prop#L39

**Comment by SirRGB** [comment]
fastboot getvar unlocked

Sollte true oder false zurückgeben, aber auch nur im bootloader. Hab jetzt nix mit adb gefunden...

[sys.oem_unlock_allowed]: [1] ist wahrscheinlich nicht hilfreich...
