### ISSUE TITLE
Add support for `A85`

### ISSUE THREAD

**Issue by serhii198610** [openandroidinstaller-dev/openandroidinstaller#581]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

blackview

### Name

a85

### Device code

a85

### Model

a85

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
