### ISSUE TITLE
Add support for `HWMAR`

### ISSUE THREAD

**Issue by ElectricBoy2023** [openandroidinstaller-dev/openandroidinstaller#583]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Huawei

### Name

P30 lite (Nova 4e)

### Device code

HWMAR

### Model

MAR-L21A

### Device images

```Markdown
I would like to install a custom OS and recovery, but I can't find any. Sorry. :(
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
I couldn't find any links, sorry for that, but if you search and add, it would be greatly appreciated. :)
```

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
