### ISSUE TITLE
Add support for `Pixi3-10_WiFi`

### ISSUE THREAD

**Issue by arose876** [openandroidinstaller-dev/openandroidinstaller#586]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

alcatel

### Name

pixi 3 10

### Device code

sargo

### Model

g0d0

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
.........../
```

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
