### ISSUE TITLE
Add support for `J24`

### ISSUE THREAD

**Issue by dmrstuvwxyz** [openandroidinstaller-dev/openandroidinstaller#590]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

vortex

### Name

j24

### Device code

j24

### Model

j24

### Device images

```Markdown
- any available custom rom
any available recovery rom
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
no additional comments
```

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
