### ISSUE TITLE
Add support for `Oppo a77s`

### ISSUE THREAD

**Issue by GMXO** [openandroidinstaller-dev/openandroidinstaller#598]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Oppo

### Name

Oppo a77s

### Device code

OP5637L1

### Model

CPH2473

### Device images

```Markdown
https://drive.google.com/file/d/1HiwJc6qBlPX-WBQHIdQIzTOPNC9316sp/view
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
