### ISSUE TITLE
Add support for `HWRNE`

### ISSUE THREAD

**Issue by kusaskan** [openandroidinstaller-dev/openandroidinstaller#601]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Huawei

### Name

Mate 10 lite

### Device code

Device with code 'HWRNE' is not supported yet.

### Model

RNE-L21

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
Huawei made it basically impossible to unlock bootloaders... so I doubt there is anything we can do here.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
