### ISSUE TITLE
Add support for `ice`

### ISSUE THREAD

**Issue by Paimon93** [openandroidinstaller-dev/openandroidinstaller#611]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Redmi                                                                                       

### Name

ice

### Device code

C6LJDQ79CIUOKZ99 

### Model

220733SG

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
