### ISSUE TITLE
Add support for `mid1105_mp`

### ISSUE THREAD

**Issue by Sterlingmay100** [openandroidinstaller-dev/openandroidinstaller#614]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

onn.

### Name

onn. tablet Pro 11.6 

### Device code

mid1105_mp

### Model

100043279

### Device images

```Markdown
Could not find
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
This is a Walmart brand tablet that needs a new device image (the current one is very buggy) I am willing to be the tester on the device.
```

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
