### ISSUE TITLE
Add support for Wiko T50 `W-P861`

### ISSUE THREAD

**Issue by canegunn607** [openandroidinstaller-dev/openandroidinstaller#617]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

wiko

### Name

t50

### Device code

W-P861

### Model

Wiko T50

### Device image
Twrp ,magisk

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
