### ISSUE TITLE
Add support for `J24`

### ISSUE THREAD

**Issue by testmonkei** [openandroidinstaller-dev/openandroidinstaller#618]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

vortex (unisoc sc9863a)

### Name

j24

### Device code

na

### Model

j24

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
na
```

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
