### ISSUE TITLE
Add support for `CPH1909`

### ISSUE THREAD

**Issue by ZG089** [openandroidinstaller-dev/openandroidinstaller#624]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

OPPO

### Name

OPPO A5s

### Device code

CPH1909

### Model

CPH1909

### Device images

```Markdown
Stock rom : https://drive.google.com/file/d/1pnK6RZo7msV5rKJuRSqJEP29vcnQ2CJx/view?usp=share_link
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
