### ISSUE TITLE
Add support for `lisa`

### ISSUE THREAD

**Issue by sergiomarins** [openandroidinstaller-dev/openandroidinstaller#627]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Xiaomi

### Name

Xiaomi Mi 10 Lite 5G NE

### Device code

lisa

### Model

2109119DG

### Device images

Xiaomi HyperOS 1.0.9.0.UKOEUXM

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
