### ISSUE TITLE
Add support for `SL004T`

### ISSUE THREAD

**Issue by GBbDaBby** [openandroidinstaller-dev/openandroidinstaller#629]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

koobee

### Name

koobee k100

### Device code

SL004T

### Model

SL004T

### Device images

```Markdown
https://dumps.tadiphone.dev/dumps/koobee/sl004t/-/blob/sys_mssi_32_ago_ww-user-12-SP1A.210812.016-1669984765-release-keys/system/odm/firmware
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
all of its files are at gitlab Android dumps
```

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
