### ISSUE TITLE
Add support for `SH-06F`

### ISSUE THREAD

**Issue by rishansenarath** [openandroidinstaller-dev/openandroidinstaller#636]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

sharp

### Name

aquos pad

### Device code

Japan

### Model

SH 06-F

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
please request any supported custom roms for my device
```

**Comment by tsterbak** [comment]
I cannot find any TWRP and custom ROM support for this device.

So I close this for now. If you think this is wrong and provide more information, we can reopen it again.
