### ISSUE TITLE
Add support for `I15_Pro_Max`

### ISSUE THREAD

**Issue by TonyRamos24** [openandroidinstaller-dev/openandroidinstaller#637]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Welcome

### Name

welcome I15 Pro Max

### Device code

Device with code 'I15_Pro_Max' is not supported yet.

### Model

I15 Pro Max

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find anything about this device online. So it is unlikely that there is and will be TWRP and custom ROM support.

I close this for now. If you think this is wrong and provide more information, we can reopen it again.
