### ISSUE TITLE
Add support for `8505F`

### ISSUE THREAD

**Issue by DIAN00978BH** [openandroidinstaller-dev/openandroidinstaller#640]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

lenovo

### Name

lenovo TB-8505F

### Device code

8505F

### Model

8505F

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find anything about this device online. So it is unlikely that there is and will be TWRP and custom ROM support.

I close this for now. If you think this is wrong and provide more information, we can reopen it again.
