### ISSUE TITLE
Add support for `M10_PRO_EEA`

### ISSUE THREAD

**Issue by Krydys** [openandroidinstaller-dev/openandroidinstaller#641]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Pritom

### Name

M10_PRO_EEA

### Device code

M10_PRO_EEA

### Model

M10_PRO_EEA

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find anything about this device online. So it is unlikely that there is and will be TWRP and custom ROM support.

I close this for now. If you think this is wrong and provide more information, we can reopen it again.
