### ISSUE TITLE
Add support for `rhodep`

### ISSUE THREAD

**Issue by Bringolino** [openandroidinstaller-dev/openandroidinstaller#643]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Motorola

### Name

Moto G82 5G (XT2225-1)

### Device code

ZY22GX3H88

### Device images

```Markdown
https://motostockrom.com/motorola-moto-g82-5g-xt2225-1
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
Moto G82 5G (XT2225-1) RHODEP
```

**Comment by tsterbak** [comment]
I cannot find anything about this device online. So it is unlikely that there is and will be TWRP and custom ROM support.

I close this for now. If you think this is wrong and provide more information, we can reopen it again.

**Comment by tsterbak** [comment]
I cannot find anything about this device online. So it is unlikely that there is and will be TWRP and custom ROM support.

I close this for now. If you think this is wrong and provide more information, we can reopen it again.
