### ISSUE TITLE
Add support for `a15`

### ISSUE THREAD

**Issue by AdelioM-0404** [openandroidinstaller-dev/openandroidinstaller#645]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Vietinam

### Name

Galaxy A15

### Device code

673577

### Model

SM-A155F/DSN

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find anything about this device online. So it is unlikely that there is and will be TWRP and custom ROM support.

I close this for now. If you think this is wrong and provide more information, we can reopen it again.
