### ISSUE TITLE
Add support for `yellowtail`

### ISSUE THREAD

**Issue by Aurimarvenega** [openandroidinstaller-dev/openandroidinstaller#647]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

dell venue 8 hspa+

### Name

t02d002

### Device code

venue3830

### Model

t02d

### Device images

```Markdown
https://www.dell.com/support/product-details/pt-br/servicetag/0-K2ZYdEZtajZUbEZaNlpaQlFRWjM4Zz090/overview
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find anything about this device online. So it is unlikely that there is and will be TWRP and custom ROM support.

I close this for now. If you think this is wrong and provide more information, we can reopen it again.
