### ISSUE TITLE
Add support for `OP4883`

### ISSUE THREAD

**Issue by Infosankey** [openandroidinstaller-dev/openandroidinstaller#649]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Oppo

### Name

OP4883

### Device code

4883

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
Want to flash a new os on this device but it says the device is not supported yet
```

**Comment by tsterbak** [comment]
I cannot find anything about this device online. So it is unlikely that there is and will be TWRP and custom ROM support.

I close this for now. If you think this is wrong and provide more information, we can reopen it again.
