### ISSUE TITLE
Add support for `lime`

### ISSUE THREAD

**Issue by DesenvolvedorDene** [openandroidinstaller-dev/openandroidinstaller#650]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

xiomi

### Name

redmi 9t

### Device code

lime

### Model

READMI 9T

### Device images

```Markdown
NAO SEI
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
QUERO ATUALIZAR
```

**Comment by tsterbak** [comment]
I cannot find anything about this device online. So it is unlikely that there is and will be TWRP and custom ROM support.

I close this for now. If you think this is wrong and provide more information, we can reopen it again.
