### ISSUE TITLE
Add support for `cyprus64`

### ISSUE THREAD

**Issue by beniciodomin95** [openandroidinstaller-dev/openandroidinstaller#652]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Motorola

### Name

moto e40

### Device code

cyprus64

### Model

XT2159-1

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find anything about this device online. So it is unlikely that there is and will be TWRP and custom ROM support.

I close this for now. If you think this is wrong and provide more information, we can reopen it again.
