### ISSUE TITLE
Add support for `TECNO-KF6i`

### ISSUE THREAD

**Issue by meshack-vs-you-all** [openandroidinstaller-dev/openandroidinstaller#654]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

TECNO

### Name

Tecno Spark 7 Pro

### Device code

TECNO-KF6i

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find anything about this device online. So it is unlikely that there is and will be TWRP and custom ROM support.

I close this for now. If you think this is wrong and provide more information, we can reopen it again.
