### ISSUE TITLE
Add support for `fijisc`

### ISSUE THREAD

**Issue by EvertoonSR** [openandroidinstaller-dev/openandroidinstaller#657]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Motorola

### Name

Moto e 6i

### Device code

fijisc

### Model

XT2053-5

### Device images

```Markdown
https://www.tudocelular.com/Motorola/fichas-tecnicas/n6687/Motorola-Moto-E6i.html
```

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

### Additional context

```Markdown
É um dispositivo basico, porém com alta demanda em procura de uma custo Rom, e dificil de se encotrar metodos de instalaçoes.
```

**Comment by tsterbak** [comment]
I cannot find anything about this device online. So it is unlikely that there is and will be TWRP and custom ROM support.

I close this for now. If you think this is wrong and provide more information, we can reopen it again.
