### ISSUE TITLE
Add support for `scx35_sp7731geaplus_pad_hd`

### ISSUE THREAD

**Issue by damian234321** [openandroidinstaller-dev/openandroidinstaller#659]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Google

### Name

Pixel 3a

### Device code

sargo

### Model

G020F

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
Not sure why this didn't work for you. The Pixel 3a is one of my default testing devices, so it should work perfectly.

Can you elaborate what you tried?

**Comment by SirRGB** [comment]
The codename posted seems to be a really odd tablet?

https://forum.gsmhosting.com/vbb/f906/ikon-ik-785-firmware-cm2-read-2493797/

**Comment by tsterbak** [comment]
Ok, then I'll close it for now :)
