### ISSUE TITLE
Add support for `gts9uwifi`

### ISSUE THREAD

**Issue by ragnelli** [openandroidinstaller-dev/openandroidinstaller#660]
### Is your device already requested?

- [X] I have searched the existing issues

### Brand

Samsung

### Name

Galaxy Tab S9 Ultra

### Device code

gts9uwifi

### Model

SM-X910

### Do you own the device and would be willing to test the installer?

- [X] I own the device and am willing to test the installer on it.

**Comment by tsterbak** [comment]
I cannot find anything about this device online. So it is unlikely that there is and will be TWRP and custom ROM support.

I close this for now. If you think this is wrong and provide more information, we can reopen it again.

**Comment by ragnelli** [comment]
I've found the TWRP for this device!
