### ISSUE TITLE
Allow a steps for flashing additional software

### ISSUE THREAD

**Issue by tsterbak** [openandroidinstaller-dev/openandroidinstaller#7]
After sideloading LineageOS there should be a step to install additional software:
- Google Apps and Services
- F-droid (with an toggle switch at the beginning)
- microG
- Magicks
- other?

**Comment by MagicLike** [comment]
May I add the Aurora Store to the list?

**Comment by MagicLike** [comment]
I mean it would be a fast way to have PlayStore apps available, but yeah it is also directely available from F-Droid...
