### ISSUE TITLE
Using Peertube as video provider

### ISSUE THREAD

**Issue by MagicLike** [openandroidinstaller-dev/openandroidinstaller#71]
I just saw the video embedded on the website and had an idea: Why not use [Peertube](https://joinpeertube.org) as a video provider for such showcases and in general for update videos?

If you are on the look for a relatively small, but well managed instance with great storage options, I can recommend [Peertube.TV](https://peertube.tv).

**Comment by tsterbak** [comment]
I will look into Peertube for that. Might be interesting as soon as more video demos and updates come in.

**Comment by tsterbak** [comment]
Do you want to open a similar issue on the Website repository? https://github.com/openandroidinstaller-dev/openandroidinstaller-dev.github.io

**Comment by MagicLike** [comment]
> Do you want to open a similar issue on the Website repository? https://github.com/openandroidinstaller-dev/openandroidinstaller-dev.github.io

Done!

https://github.com/openandroidinstaller-dev/openandroidinstaller-dev.github.io/issues/5

**Comment by tsterbak** [comment]
Continued here: https://github.com/openandroidinstaller-dev/openandroidinstaller-dev.github.io/issues/5
