### ISSUE TITLE
Support for poco f3 plz. For me to install evolution x rom on it.

### ISSUE THREAD

**Issue by ghost** [openandroidinstaller-dev/openandroidinstaller#79]
The tool's awesome.

**Comment by tsterbak** [comment]
Hey @Bizz912, thanks a lot! :)

You mean this device? https://wiki.lineageos.org/devices/alioth/
I will try to add support for Xiaomi devices in the next minor release on the weekend. The bootloader process is horrible, but for people with unlocked bootloaders it should be smooth.

Would you be able to test the new release?

**Comment by Bizz912** [comment]
As soon as I get that phone in place of galaxy a32 4g.

**Comment by zachvlat** [comment]
I can test it also with my phone

**Comment by Bizz912** [comment]
> I can test it also with my phone

Do let us know man.

**Comment by Bizz912** [comment]
Can account spoofer be added for unlocking bootloaders on poco phones?

**Comment by tsterbak** [comment]
I don't know what an account spoofer exactly is so I don't know :sweat_smile:
Do you have any resources to read about this procedure?

**Comment by Bizz912** [comment]
Basically tricking the software or device into using randomly generated account, something similar to how Aurora store uses a dummy account.

**Comment by Bizz912** [comment]
https://en.wikipedia.org/wiki/Login_spoofing

**Comment by Bizz912** [comment]
@tsterbak Btw is oneplus 8 supported? Its not on the list.

**Comment by Bizz912** [comment]
Its alright, I am also looking at op8 for usb 3.1, display port. I can't seem to figure the unlock bootloader part either on poco.

**Comment by SirRGB** [comment]
https://github.com/openandroidinstaller-dev/openandroidinstaller/pull/343

Untested, but was merged already.
Maybe open a new issue with login spoofing?

**Comment by tsterbak** [comment]
Merged and officially still untested.
