### ISSUE TITLE
Device code issue with zeroltexx

### ISSUE THREAD

**Issue by tsterbak** [openandroidinstaller-dev/openandroidinstaller#81]
The Samsung Galaxy S6 sometimes shows up with code "zerolte" and thus the config is not found. Fix this:
https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/main/openandroidinstaller/assets/configs/zeroltexx.yaml

**Comment by MagicLike** [comment]
@tsterbak Fixed in https://github.com/openandroidinstaller-dev/openandroidinstaller/pull/121/commits/c800eb422a86aae7277d3310071a3ef52a9b6407
