### ISSUE TITLE
Use adb wait-for-recovery and adb wait-for-sideload

### ISSUE THREAD

**Issue by tsterbak** [openandroidinstaller-dev/openandroidinstaller#83]
Maybe a lot of the sleep commands in the flashing steps can be removed by properly waiting. This also should increase stability of the process. Might not be supported on all devices or TWRP version?

To be tested.

**Comment by tsterbak** [comment]
Released in 0.4.1-beta

**Comment by EdoSecco** [comment]
Not sure if it is the right thread, but I've tried two times installing LineageOS on Samsung A5 2017, and after correctly install TWRP, and [having the phone in recovery mode](https://d4.alternativeto.net/Ysdhc5-2_UdRZufNkviGetv21QmwdCGMf8j4Ol-bFyo/rs:fit:2400:2400:0/g:ce:0:0/YWJzOi8vZGlzdC9zL3RlYW0td2luLXJlY292ZXJ5LXByb2plY3QtdHdycC1fMjA1NDE2X2Z1bGwucG5n.jpg), I'm not able to go beyond this:
>$adb -d reboot recovery
>$adb -d wait-for-recovery
