### ISSUE TITLE
Support for Xiaomi Redmi Note 9 Pro

### ISSUE THREAD

**Issue by RaptaG** [openandroidinstaller-dev/openandroidinstaller#85]
I really wanna use /e/OS with my phone without going through the stressing steps of the manual installation

**Comment by RaptaG** [comment]
Should I generate a config or something?

**Comment by tsterbak** [comment]
If creating a config works for you, I would be happy to review it! :)

You can find instructions here: https://github.com/openandroidinstaller-dev/openandroidinstaller#how-to-contribute-your-own-installation-configurations

Let me know if you need any help :)

**Comment by RaptaG** [comment]
So the config is basically the steps needed to get the ROM working the phone?

**Comment by tsterbak** [comment]
> So the config is basically the steps needed to get the ROM working the phone?

Yes, exactly. Some steps are already fully automated the won't appear in the config. You mainly need to provide steps to get the TWRP recovery booted on phone. And instructions and support to unlock the bootloader.

**Comment by RaptaG** [comment]
Aw man, it's sure I'll screw this up

**Comment by RaptaG** [comment]
The Mi Unlock tool (the tool used to unlock the bootloader in Xiaomi devices) doesn't seem to work on my end.

**Comment by tsterbak** [comment]
I remember it was a pain to find a version that worked with my device (a Mi 9 Lite). Are you using the official version for Windows?
I guess the version that worked for me in the end was `miflash_unlock-en-6.5.406-31`. Not sure why only that version worked for me, maybe I had different issues...
What's the issue you are facing?

**Comment by RaptaG** [comment]
It says it failed because I didn't enable unlocking in the Mi Unlock status, which is wrong because I did.

**Comment by RaptaG** [comment]
> Are you using the official version for Windows?

Yes

**Comment by tsterbak** [comment]
> It says it failed because I didn't enable unlocking in the Mi Unlock status, which is wrong because I did.

I'm not 100% sure what kind if issue I faced, but if I recall correctly, it was a similar one. Only one version I tried worked and recognized it correctly... but a lot of googling (with duckduckgo) went into it and stupidly I didn't document my process...

**Comment by tsterbak** [comment]
Has been released with 0.5.0.

Feel free to report your experience with the new release.
