### ISSUE TITLE
Add support for Samsung Galaxy J7 TMobile version

### ISSUE THREAD

**Issue by Dr-Axen** [openandroidinstaller-dev/openandroidinstaller#86]
My phone is detected as **j7eltetmo**. I suspect it might be able to use the same config as **j7elte**. It would also be nice to have an option to choose from the list if the detection fails to match exactly.

**Comment by tsterbak** [comment]
The selection list might be an interesting option :thinking: I decided to allow only exact matches, so people cannot just select something and totally wreck their phone. 

One option to try the tool for now is the following:
-  Download the config file here: https://github.com/openandroidinstaller-dev/openandroidinstaller/blob/main/openandroidinstaller/assets/configs/j7elte.yaml
- Change the name of the file and the devicecode in the file to "j7eltetmo"
- place the file in the same directory as the openandroidinstaller executable
- Now you should be able to run the installation from this config file

If that works fine for you, I can put the device code to the list of alternative device codes for "j7elte". :slightly_smiling_face:

**Comment by Dr-Axen** [comment]
I am trying to test it, but running into another issue. This phone is quite old, and on the list of discontinued devices in LineageOS, so it's difficult to find a recent image for it. I picked a few and renamed with the correct device id, but the app does not like either of them:

- RROS-Q-8.5.9-20200829-j7eltetmo-Unofficial.zip
- Havoc-OS-v4.5-20210524-j7eltetmo-Unofficial.zip
- PixelExperience_Plus_j7eltetmo-10.0-20200725-0537-UNOFFICIAL.zip

I suspect there is something in the name I did not get right.
 
![Screenshot from 2023-02-23 10-44-22](https://user-images.githubusercontent.com/121208683/220962459-55b70827-5aa2-406c-96a7-9410fe09c2de.png)

**Comment by tsterbak** [comment]
Thank you for trying again! :)
That looks good so far. Can you point me to where I can get one of the images?

I suspect I know the issue. The installer tries to do some basic checks on the ROM image and the TWRP. For the ROM it basically checks if the device code is in the supported devices in the metadata of the image. You can find the metadata in `/META-INF/com/android/metadata` in the zip file. The supported devices are then listed under `pre-device`. If it's listed there, you could send me the log file if you want, so I can further investigate the issue. You can also share the config file you are currently using if you want.

**Comment by Dr-Axen** [comment]
I used this list to get the images:
https://www.getdroidtips.com/custom-rom-samsung-galaxy-j7/.
I changed the metadata and got a bit further, but it seems I ran into this
issue: https://github.com/Benjamin-Dobell/Heimdall/issues/347.
I am attaching a log file for your reference.

**Comment by dumblob** [comment]
OT: I was considering my Samsung J5 to get

**Comment by tsterbak** [comment]
> I used this list to get the images: https://www.getdroidtips.com/custom-rom-samsung-galaxy-j7/. I changed the metadata and got a bit further, but it seems I ran into this issue: [Benjamin-Dobell/Heimdall#347](https://github.com/Benjamin-Dobell/Heimdall/issues/347). I am attaching a log file for your reference.

Hm, that's curious, for the `j7elte` (and also for the a5xelte mentioned in the issue on heimdall) it works without issues :thinking: 
Maybe there are subtle differences in devices or something.
What you could try is to use a different USB-cable and/or USB-Port. That sometimes is magic for some reason...

**Comment by tsterbak** [comment]
> OT: I was considering my Samsung J5 to get some love at some point and the work on J7 might benefit also J5 devices (or maybe not) - firmwares for J5 are also on https://www.getdroidtips.com/custom-rom-galaxy-j5-2016/ (e.g. https://forum.xda-developers.com/t/blissroms-14-7-r-for-j5-2016-sm-j510x-vanilla-unofficial.4199195/ as I have SM-J510FN).

You could open a new issue for the J5 and if you want you can even start with the config of the J7, modify it (https://github.com/openandroidinstaller-dev/openandroidinstaller/issues/86#issuecomment-1441421442) and try it with your device :) If that works well, you could open a PR with the new config.
