### ISSUE TITLE
[ One Plus 6T ] Failed to load config for device with code OnePlus6TSingle

### ISSUE THREAD

**Issue by JxJxxJxJ** [openandroidinstaller-dev/openandroidinstaller#91]
This happens after clicking "Search for device". I know a `fajita.yaml` file exists in the `config/` directory, but somehow it does not match my phone.

![image](https://user-images.githubusercontent.com/103049321/221563838-9b9c62ae-c26e-4d70-b37d-400b01a4b542.png)

I'm using [openandroidinstaller-v0.4.0-beta-ubuntu-latest.zip](https://github.com/openandroidinstaller-dev/openandroidinstaller/releases/download/v0.4.0-beta/openandroidinstaller-v0.4.0-beta-ubuntu-latest.zip)'s appimage  in Arch.

**Comment by tsterbak** [comment]
Hey, thanks for testing the tool and reporting this issue! :slightly_smiling_face: 
Currently, only the OnePlus6T device is supported because I wasn't aware that there is a "OnePlus6TSingle" :sweat_smile: This issue with the device code will be addressed in the next minor release, then everything should work

**Comment by JxJxxJxJ** [comment]
May I apply a small patch myself? If it's easy enough I wouldn't mind doing it. Keep up with this project, it's great :)

**Comment by tsterbak** [comment]
Thank you! :)
Of course! I would be happy to receive a patch for the issue :slightly_smiling_face:  (and patches in general :grin: )

**Comment by MagicLike** [comment]
Any updates on this?

**Comment by tsterbak** [comment]
> Any updates on this?

I will push a fix for it soon, but I want to do some research on the specific device and if there are any known issues with it.

**Comment by MagicLike** [comment]
> > Any updates on this?
> 
> I will push a fix for it soon, but I want to do some research on the specific device and if there are any known issues with it.

Alright!

**Comment by tsterbak** [comment]
Addressed in #119 

@JxJxxJxJ Could you test again when the new release is out?

**Comment by tsterbak** [comment]
@JxJxxJxJ In the new release, there is support for this device now. Give it a try and let me know if it works for you :slightly_smiling_face:

**Comment by JxJxxJxJ** [comment]
I believe I won't be able to test it in these days, but awesome!
