### ISSUE TITLE
App doesn't open on Macbook Pro "13 M1 2020

### ISSUE THREAD

**Issue by LightYagami28** [openandroidinstaller-dev/openandroidinstaller#99]
Am I into binary programming for M1 Apple Silicon?

**Comment by tsterbak** [comment]
Yes, currently ARM CPUs are not supported since I don't have an appropriate build system available.
You could build it yourself if you want given the instructions in the README. Let me know if you have any questions :)

**Comment by freechelmi** [comment]
Should be marked duplicate of #31  and closed
